/**
 * PPT Lesson API — cache-first, backend second, offline fallback third.
 *
 * Flow:
 *  1. Check Firestore cache (shared_ppt_lessons_v2/{lessonKey})
 *  2. If cached slides exist → return instantly (source: "cache")
 *  3. Else call backend (/api/ppt-lesson) with mobile-aware short timeout
 *  4. If backend succeeds → cache result → return (source: "backend")
 *  5. If backend fails/times out → build offline slides from chapter data (source: "fallback")
 *
 * Mobile vs desktop:
 *  - Mobile gets a 20-second timeout so users are never stuck waiting
 *  - Desktop gets 60 seconds (Render cold start can take ~45 s)
 */

import { API_URL } from './api';
import { db } from './firebase';
import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';

/** Build version — printed on every PPT call so we can see in production
 *  whether the user is on the new bundle or a stale cached one. */
export const PPT_BUILD_VERSION = 'ppt-2026-05-26-r4';

/* ─── Types ─────────────────────────────────────────────────────────────── */

export type DeepPptQuestion = {
  type: 'MCQ' | '1-mark' | '2-mark' | '3-mark' | 'case-based' | 'assertion-reason' | string;
  question: string;
  answer: string;
  explanation?: string;
};

export type DeepPptSlide = {
  slideNumber: number;
  layout: 'title' | 'concept' | 'diagram' | 'example' | 'table' | 'question' | 'revision' | string;
  title: string;
  subtitle?: string;
  bullets: string[];
  teacherNotes?: string;
  visualSuggestion?: string;
  diagramPrompt?: string;
  example?: string;
  examFocus?: string;
  rememberThis?: string;
  commonMistake?: string;
  questions?: DeepPptQuestion[];
};

export type DeepPptLesson = {
  id: string;
  chapterId: string;
  classLevel: string;
  subject: string;
  chapterTitle: string;
  title: string;
  promptVersion?: string;
  generatedBy?: string;
  slides: DeepPptSlide[];
  /** Added by cache-first layer — "cache" | "backend" | "fallback" */
  source?: string;
  /** Quality tag — "full_ai" only when backend returns >=15 chapter-specific slides. */
  quality?: 'full_ai' | 'quick_fallback';
  /** True when slides are a temporary client-built guide, not real AI lesson. */
  isFallback?: boolean;
  /** False when slides are a fallback — PDF/PPT export is blocked. */
  canExport?: boolean;
  /** Friendly message when source is "fallback" */
  fallbackMessage?: string;
};

export type DeepPptLessonRequest = {
  classLevel: string | number;
  subject: string;
  chapterTitle: string;
  chapterId?: string;
  topics?: string[];
  examGoal?: string;
  forceRefresh?: boolean;
  /** Optional chapter summary for offline fallback slides */
  summary?: string;
  /** Optional list of sub-topics for fallback slide content */
  concepts?: string[];
};

/* ─── Helpers ────────────────────────────────────────────────────────────── */

// v4: rolled forward with the new 18-slide chapter-deep prompt. v3 docs are
// abandoned because v3 was generated by the 22-slide prompt that produced
// inconsistent results.
const PPT_COLLECTION = 'shared_ppt_lessons_v4';

function isMobile(): boolean {
  if (typeof navigator === 'undefined') return false;
  return /Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
}

function makeLessonKey(payload: DeepPptLessonRequest): string {
  const id = payload.chapterId || payload.chapterTitle.toLowerCase().replace(/\s+/g, '-');
  return `${payload.classLevel}_${payload.subject}_${id}`.replace(/[^a-zA-Z0-9_-]/g, '_');
}

/* ─── Quality validation — reject cached fallbacks ───────────────────────── */

/** Generic placeholder phrases that identify a fallback-quality lesson. */
const PLACEHOLDER_PHRASES = [
  'Study this concept thoroughly for your exams',
  'Refer to your NCERT textbook for detailed explanations',
  'Practice related questions to reinforce your understanding',
  'Full AI lesson is being prepared',
  'Quick Study Guide',
  'Define the main concept of',
  'State the key principles or laws',
  'Key Idea #1',
  'Key Idea #2',
  'Slide title',
];

/** Returns true if the lesson is a high-quality full AI lesson, not a fallback. */
function isHighQualityLesson(lesson: DeepPptLesson): boolean {
  if (!lesson || !Array.isArray(lesson.slides)) return false;
  // Reject explicit fallback tags
  if (lesson.isFallback === true) return false;
  if (lesson.quality === 'quick_fallback') return false;
  // Must have a reasonable number of slides — 14+ matches backend's 18-slide
  // target with a small tolerance for AI dropping a slide or two.
  if (lesson.slides.length < 14) return false;
  // Must not contain placeholder phrases
  const text = lesson.slides
    .map(s => [s.title, ...(s.bullets || []), s.subtitle, s.example].filter(Boolean).join(' '))
    .join(' ');
  for (const phrase of PLACEHOLDER_PHRASES) {
    if (text.includes(phrase)) return false;
  }
  return true;
}

/* ─── Firestore cache ────────────────────────────────────────────────────── */

async function getCached(lessonKey: string): Promise<DeepPptLesson | null> {
  try {
    const snap = await getDoc(doc(db, PPT_COLLECTION, lessonKey));
    if (!snap.exists()) return null;
    const data = snap.data() as DeepPptLesson;
    if (!data.slides?.[0]?.slideNumber) return null; // old format — ignore
    // Reject cached fallbacks — these were saved before the quality gate or
    // by older code that didn't distinguish full lessons from fallbacks.
    if (!isHighQualityLesson(data)) return null;
    return data;
  } catch {
    return null; // Firestore unavailable — fall through
  }
}

async function saveCache(lessonKey: string, lesson: DeepPptLesson): Promise<void> {
  // Trust the backend's quality gate. Only refuse to cache obvious fallbacks.
  if (!lesson || !Array.isArray(lesson.slides) || lesson.slides.length < 10) return;
  if (lesson.isFallback === true || lesson.quality === 'quick_fallback') return;
  try {
    await setDoc(doc(db, PPT_COLLECTION, lessonKey), {
      ...lesson,
      id: lessonKey,
      quality: 'full_ai',
      isFallback: false,
      canExport: true,
      updatedAt: serverTimestamp(),
    });
  } catch {
    // Non-fatal — just means next load will call backend again
  }
}

/* ─── Backend call ───────────────────────────────────────────────────────── */

async function fetchFromBackend(
  payload: DeepPptLessonRequest,
  timeoutMs: number,
  reqId: string,
): Promise<DeepPptLesson> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const url = `${API_URL}/api/ppt-lesson`;
  console.log(`[ppt ${reqId}] → POST ${url}  timeout=${timeoutMs}ms`, payload);

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Ppt-ReqId': reqId },
      body: JSON.stringify(payload),
      signal: controller.signal,
      // Bypass any HTTP/SW caching — we never want a stale 500 served to us.
      cache: 'no-store',
    });
    console.log(`[ppt ${reqId}] ← HTTP ${res.status} from backend`);

    if (!res.ok) {
      let body: any = null;
      try { body = await res.json(); } catch { /* ignore */ }
      console.warn(`[ppt ${reqId}] backend error body:`, body);
      throw new Error(body?.error || `HTTP ${res.status}`);
    }

    const data = await res.json();
    if (!data.lesson || !Array.isArray(data.lesson.slides)) {
      throw new Error('Invalid lesson response from backend.');
    }
    console.log(`[ppt ${reqId}] ← lesson received  slides=${data.lesson.slides.length}  fromCache=${data.fromCache}`);
    return data.lesson as DeepPptLesson;
  } finally {
    clearTimeout(timer);
  }
}

/* ─── Offline fallback slides ────────────────────────────────────────────── */

/**
 * Quick fallback shown only when the backend can't reach Gemini.
 * Deliberately small (3 slides) and visually clearly NOT a real lesson, so
 * users see at a glance that the full lesson hasn't loaded yet. NEVER cached,
 * NEVER exported.
 */
function buildFallbackSlides(payload: DeepPptLessonRequest): DeepPptSlide[] {
  const title = payload.chapterTitle;
  const cls = String(payload.classLevel);
  const sub = payload.subject;
  const errorReason = (typeof window !== 'undefined' && (window as any).__lastPptError) || 'no error captured';

  return [
    {
      slideNumber: 1,
      layout: 'title',
      title: `⏳ ${title}`,
      subtitle: `The full AI lesson could not be loaded. Diagnostic info below.`,
      bullets: [],
    },
    {
      slideNumber: 2,
      layout: 'concept',
      title: 'Diagnostic info (share this if support asks)',
      bullets: [
        `Reason: ${errorReason}`,
        `Build: ${PPT_BUILD_VERSION}`,
        `API: ${API_URL}`,
        `Class ${cls} · ${sub} · "${title}"`,
        `Action: close this modal and tap "PPT Lesson" again — backend should be warm now.`,
      ],
    },
    {
      slideNumber: 3,
      layout: 'concept',
      title: `What you can do right now`,
      bullets: [
        `Close this and reopen "PPT Lesson" — the lesson usually loads on the second try.`,
        `Open Practice Arena to attempt MCQ questions on ${title}.`,
        `Open Skills Lab to revise related topics.`,
      ],
    },
  ];
}

/* ─── Main exported function ─────────────────────────────────────────────── */

export async function getDeepPptLesson(payload: DeepPptLessonRequest): Promise<DeepPptLesson> {
  const lessonKey = makeLessonKey(payload);
  const mobile = isMobile();
  const reqId = Math.random().toString(36).slice(2, 8);
  // Desktop: 90 s. Backend retries Gemini up to 3 times internally
  // (~30 s) plus Render free-tier cold start (~30 s) = up to 60 s. 90 s gives
  // headroom. Mobile keeps 15 s hard cap.
  const timeoutMs = mobile ? 15_000 : 90_000;

  console.log(`[ppt ${reqId}] START  build=${PPT_BUILD_VERSION}  mobile=${mobile}  key=${lessonKey}  API=${API_URL}`);

  // Signal cold-start banner after 5 s (only if we end up calling backend)
  let slowTimer: ReturnType<typeof setTimeout> | null = null;

  try {
    // ── Step 1: Firestore cache (instant on any device) ──────────────────
    const cached = await getCached(lessonKey);
    if (cached) {
      console.log(`[ppt ${reqId}] CACHE HIT  slides=${cached.slides.length}`);
      return { ...cached, source: 'cache', id: lessonKey };
    }
    console.log(`[ppt ${reqId}] cache MISS — calling backend`);

    // ── Step 2: Backend API ───────────────────────────────────────────────
    slowTimer = window.setTimeout(() => {
      window.dispatchEvent(new CustomEvent('syllab:ai-slow', { detail: { source: 'pptLesson' } }));
    }, 5000);

    // Backend already retries Gemini 3x internally, so one frontend attempt
    // is enough. Desktop gets the full 60s budget per attempt.
    let lesson: DeepPptLesson | null = null;
    let lastError = '';
    try {
      lesson = await fetchFromBackend(payload, timeoutMs, reqId);
      if (lesson && Array.isArray(lesson.slides) && lesson.slides.length >= 10) {
        console.log(`[ppt ${reqId}] ✅ BACKEND OK  slides=${lesson.slides.length}`);
      } else {
        lastError = `thin response: slides=${lesson?.slides?.length}`;
        console.warn(`[ppt ${reqId}] ❌ ${lastError}`);
        lesson = null;
      }
    } catch (backendErr) {
      lastError = (backendErr as Error)?.message || 'unknown error';
      console.warn(`[ppt ${reqId}] ❌ backend FAILED:`, lastError);
    }
    if (lesson) {
      void saveCache(lessonKey, lesson);
      return {
        ...lesson,
        source: 'backend',
        quality: 'full_ai',
        isFallback: false,
        canExport: true,
        id: lessonKey,
      };
    }
    console.warn(`[ppt ${reqId}] ⚠️ backend failed — using fallback. Reason:`, lastError);
    // Stash last error so the fallback banner can show it.
    (window as any).__lastPptError = `${lastError} · build ${PPT_BUILD_VERSION} · ${API_URL}`;

    // ── Step 3: Tiny "lesson loading" placeholder (NEVER cached, NEVER exported)
    const fallbackSlides = buildFallbackSlides(payload);
    const lastErr = (window as any).__lastPptError || 'unknown';
    return {
      id: lessonKey,
      chapterId: payload.chapterId || lessonKey,
      classLevel: String(payload.classLevel),
      subject: payload.subject,
      chapterTitle: payload.chapterTitle,
      title: `⏳ ${payload.chapterTitle} — lesson loading`,
      slides: fallbackSlides,
      source: 'fallback',
      quality: 'quick_fallback',
      isFallback: true,
      canExport: false,
      fallbackMessage: `Backend request failed (${lastErr}). Close and tap "PPT Lesson" again — backend should be warm now.`,
    };
  } finally {
    if (slowTimer !== null) clearTimeout(slowTimer);
    window.dispatchEvent(new CustomEvent('syllab:ai-fast', { detail: { source: 'pptLesson' } }));
  }
}
