/**
 * import-decks.ts — Auto-register provided slide decks (PDFs) into the app.
 *
 * Workflow:
 *   1. Drop your Gemini-made PDFs anywhere under public/decks/
 *      (filename should resemble the chapter, e.g. "Numbers 1 to 9 - Class 1.pdf"
 *       or inside a class folder like public/decks/class-1/numbers-1-to-9.pdf)
 *   2. Run:  npx tsx scripts/import-decks.ts
 *   3. It fuzzy-matches each PDF to a syllabus chapter and rewrites
 *      src/data/chapterDecks.ts. Unmatched files are listed for you to rename.
 *
 * No manual registry editing — add 5 or 500 PDFs, just re-run.
 */

import { readdirSync, statSync, writeFileSync } from 'fs';
import { join, relative, basename, extname } from 'path';
import { SYLLABUS } from '../src/data/syllabus';

const DECKS_DIR = join('public', 'decks');

function walk(dir: string): string[] {
  const out: string[] = [];
  let entries: string[] = [];
  try { entries = readdirSync(dir); } catch { return out; }
  for (const e of entries) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (extname(p).toLowerCase() === '.pdf') out.push(p);
  }
  return out;
}

const tokens = (s: string) =>
  s.toLowerCase().replace(/\.pdf$/, '').replace(/class\s*\d+/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ').split(/\s+/).filter(w => w.length > 1);

function classFromPath(p: string, fname: string): string | null {
  const m = `${p} ${fname}`.match(/class[ _-]?(\d{1,2})/i);
  return m ? m[1] : null;
}

function bestChapter(fname: string, cls: string | null) {
  const fTok = new Set(tokens(fname));
  let best: { score: number; ch: typeof SYLLABUS[number] } | null = null;
  for (const ch of SYLLABUS) {
    if (cls && String(ch.classLevel) !== cls) continue;
    const cTok = tokens(ch.title);
    if (!cTok.length) continue;
    let score = 0;
    for (const t of cTok) if (fTok.has(t)) score++;
    // fraction of the chapter title's words that the filename covers
    const norm = score / cTok.length;
    // Accept: 2+ shared words, OR a short title fully covered (e.g. "Money", "Time")
    const ok = score >= 2 || (score >= 1 && norm >= 0.5);
    if (ok && (!best || norm > best.score)) best = { score: norm, ch };
  }
  return best?.ch || null;
}

const normKey = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const pdfs = walk(DECKS_DIR);
const mapped: { key: string; url: string; title: string; cls: string }[] = [];
const unmatched: string[] = [];

for (const p of pdfs) {
  const fname = basename(p);
  const cls = classFromPath(p, fname);
  const ch = bestChapter(fname, cls);
  const url = '/' + relative('public', p).replace(/\\/g, '/');
  if (ch) mapped.push({ key: `${ch.classLevel}::${normKey(ch.title)}`, url, title: ch.title, cls: String(ch.classLevel) });
  else unmatched.push(fname);
}

// De-dupe keys (last wins) and sort
const byKey = new Map(mapped.map(m => [m.key, m]));
const entries = [...byKey.values()].sort((a, b) => (a.cls + a.title).localeCompare(b.cls + b.title));

const body = entries.map(m => `  '${m.key}': '${m.url}',  // Class ${m.cls} · ${m.title}`).join('\n');
const out = `/**
 * chapterDecks.ts — AUTO-GENERATED by scripts/import-decks.ts. Do not edit by hand;
 * drop PDFs in public/decks/ and re-run \`npx tsx scripts/import-decks.ts\`.
 *
 * Maps \`\${classLevel}::\${normalizedChapterTitle}\` → deck PDF URL.
 */

const DECKS: Record<string, string> = {
${body}
};

const norm = (s: string) => (s || '').toLowerCase().replace(/[^a-z0-9]/g, '');

export function getDeckUrl(classLevel: string | number, title: string): string | null {
  return DECKS[\`\${classLevel}::\${norm(title)}\`] || null;
}
export function hasDeck(classLevel: string | number, title: string): boolean {
  return getDeckUrl(classLevel, title) !== null;
}
`;

writeFileSync(join('src', 'data', 'chapterDecks.ts'), out, 'utf8');

console.log(`\n✅ Registered ${entries.length} deck(s) → src/data/chapterDecks.ts`);
for (const e of entries) console.log(`   • Class ${e.cls} · ${e.title}  ←  ${e.url}`);
if (unmatched.length) {
  console.log(`\n⚠️  ${unmatched.length} PDF(s) could not be matched to a chapter (rename to match the chapter title):`);
  for (const u of unmatched) console.log(`   • ${u}`);
}
