/**
 * register-generated-decks.ts — scans public/generated-decks/ and writes
 * src/data/generatedDecks.ts mapping each chapter to its generated HTML deck.
 * Exact (not fuzzy): for every syllabus chapter we check the expected file path.
 * Run after generate-slides.ts:  npx tsx scripts/register-generated-decks.ts
 */
import { existsSync, writeFileSync } from 'fs';
import { join } from 'path';
import { SYLLABUS } from '../src/data/syllabus';

const slug = (s: string) => s.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 60);
const normKey = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const entries: { key: string; url: string; label: string }[] = [];
for (const ch of SYLLABUS) {
  const board = ch.board || 'CBSE';
  const rel = join('generated-decks', board, `Class ${ch.classLevel}`, slug(ch.subject), `${slug(ch.title)}.html`);
  if (existsSync(join('public', rel))) {
    entries.push({
      key: `${ch.classLevel}::${normKey(ch.title)}`,
      url: '/' + rel.replace(/\\/g, '/'),
      label: `Class ${ch.classLevel} · ${ch.subject} · ${ch.title}`,
    });
  }
}
const byKey = new Map(entries.map(e => [e.key, e]));
const list = [...byKey.values()];

const body = list.map(e => `  '${e.key}': '${e.url}',`).join('\n');
writeFileSync('src/data/generatedDecks.ts', `/**
 * generatedDecks.ts — AUTO-GENERATED by scripts/register-generated-decks.ts.
 * Maps \`\${classLevel}::\${normalizedChapterTitle}\` → generated HTML deck URL.
 */
const GENERATED: Record<string, string> = {
${body}
};
const norm = (s: string) => (s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
export function getGeneratedDeckUrl(classLevel: string | number, title: string): string | null {
  return GENERATED[\`\${classLevel}::\${norm(title)}\`] || null;
}
`, 'utf8');

console.log(`✅ Registered ${list.length} generated decks → src/data/generatedDecks.ts`);
