/**
 * chapterDecks.ts — AUTO-GENERATED by scripts/import-decks.ts. Do not edit by hand;
 * drop PDFs in public/decks/ and re-run `npx tsx scripts/import-decks.ts`.
 *
 * Maps `${classLevel}::${normalizedChapterTitle}` → deck PDF URL.
 */

const DECKS: Record<string, string> = {
  '1::addition': '/decks/class-1/addition.pdf',  // Class 1 · Addition
  '1::measurement': '/decks/class-1/measurement.pdf',  // Class 1 · Measurement
  '1::money': '/decks/class-1/money.pdf',  // Class 1 · Money
  '1::mybody': '/decks/class-1/my-body.pdf',  // Class 1 · My Body
  '1::numbersfrom1to9': '/decks/class-1/numbers-1-to-9.pdf',  // Class 1 · Numbers from 1 to 9
  '1::numbersfrom10to20': '/decks/class-1/numbers-10-to-20.pdf',  // Class 1 · Numbers from 10 to 20
  '1::subtraction': '/decks/class-1/subtraction.pdf',  // Class 1 · Subtraction
  '1::time': '/decks/class-1/time.pdf',  // Class 1 · Time
};

const norm = (s: string) => (s || '').toLowerCase().replace(/[^a-z0-9]/g, '');

export function getDeckUrl(classLevel: string | number, title: string): string | null {
  return DECKS[`${classLevel}::${norm(title)}`] || null;
}
export function hasDeck(classLevel: string | number, title: string): boolean {
  return getDeckUrl(classLevel, title) !== null;
}
