// AUTO-GENERATED by scripts/generate-homework-curriculum.mjs — do not edit by hand.
// Class → Subject → Chapter[] for the AI Tuition Teacher dependent dropdowns.
// Classes 1–5 are hand-authored CBSE foundational chapters; 6–12 come from
// the app's NCERT solutions dataset.

export type CurriculumMap = Record<string, Record<string, string[]>>;

export const HOMEWORK_CURRICULUM: CurriculumMap = {
  "1": {
    "Mathematics": [
      "Numbers 1 to 9",
      "Numbers up to 20",
      "Addition",
      "Subtraction",
      "Shapes and Space",
      "Measurement",
      "Time",
      "Money",
      "Patterns"
    ],
    "English": [
      "The Alphabet",
      "Three Letter Words",
      "Naming Words (Nouns)",
      "Action Words (Verbs)",
      "Rhyming Words",
      "Reading Simple Sentences"
    ],
    "EVS": [
      "My Family",
      "My Body",
      "Plants Around Us",
      "Animals Around Us",
      "Good Habits",
      "Food We Eat"
    ]
  },
  "2": {
    "Mathematics": [
      "Numbers up to 100",
      "Addition with Carrying",
      "Subtraction with Borrowing",
      "Shapes",
      "Measurement of Length",
      "Time and Calendar",
      "Money",
      "Multiplication Tables",
      "Patterns"
    ],
    "English": [
      "Nouns",
      "Pronouns",
      "Verbs",
      "Adjectives",
      "Articles (a, an, the)",
      "Reading Comprehension",
      "Picture Composition"
    ],
    "EVS": [
      "Living and Non-living",
      "Plants",
      "Animals and Their Homes",
      "Our Family and Festivals",
      "Water",
      "Means of Transport"
    ]
  },
  "3": {
    "Mathematics": [
      "Numbers up to 1000",
      "Addition and Subtraction",
      "Multiplication",
      "Division",
      "Fractions",
      "Geometry - Shapes",
      "Measurement",
      "Time",
      "Money",
      "Data Handling"
    ],
    "English": [
      "Nouns and Genders",
      "Tenses",
      "Adjectives",
      "Prepositions",
      "Conjunctions",
      "Comprehension",
      "Paragraph Writing"
    ],
    "EVS": [
      "Plants and Their Parts",
      "Animals",
      "The Human Body",
      "Our Food",
      "Houses Around Us",
      "Travel and Transport",
      "Water and Air"
    ]
  },
  "4": {
    "Mathematics": [
      "Large Numbers",
      "Addition and Subtraction",
      "Multiplication",
      "Division",
      "Factors and Multiples",
      "Fractions",
      "Geometry",
      "Perimeter and Area",
      "Measurement",
      "Time",
      "Money",
      "Data Handling"
    ],
    "English": [
      "Parts of Speech",
      "Tenses",
      "Active and Passive Voice",
      "Punctuation",
      "Comprehension",
      "Letter Writing",
      "Essay Writing"
    ],
    "EVS": [
      "Plants - Adaptations",
      "Animals - Adaptations",
      "The Human Body and Senses",
      "Food and Digestion",
      "Our Environment",
      "Natural Resources",
      "Safety and First Aid"
    ]
  },
  "5": {
    "Mathematics": [
      "Large Numbers and Operations",
      "Factors and Multiples",
      "Fractions",
      "Decimals",
      "Percentage",
      "Geometry",
      "Perimeter, Area and Volume",
      "Measurement",
      "Time and Temperature",
      "Data Handling",
      "Patterns"
    ],
    "English": [
      "Parts of Speech",
      "Tenses",
      "Voice",
      "Direct and Indirect Speech",
      "Comprehension",
      "Letter and Notice Writing",
      "Story and Essay Writing"
    ],
    "EVS": [
      "Super Senses",
      "Plants and Animals",
      "The Human Body",
      "Food and Health",
      "Water and Its Uses",
      "Natural Disasters",
      "Our Environment",
      "Travel and Communication"
    ]
  },
  "6": {
    "Mathematics": [
      "Data Handling and Presentation",
      "Fractions",
      "Lines and Angles",
      "Number Play",
      "Patterns in Mathematics",
      "Perimeter and Area",
      "Playing with Constructions",
      "Prime Time",
      "Symmetry",
      "The Other Side of Zero"
    ],
    "Science": [
      "A Journey Through States of Water",
      "Beyond Earth",
      "Diversity in the Living World",
      "Exploring Magnets",
      "Living Creatures Exploring Their Characteristics",
      "Materials Around Us",
      "Measurement of Length and Motion",
      "Methods of Separation in Everyday Life",
      "Mindful Eating a Path to a Healthy Body",
      "Nature S Treasures",
      "Temperature and its Measurement",
      "The Wonderful World of Science"
    ]
  },
  "7": {
    "Mathematics": [
      "A Peek Beyond the Point",
      "A Tale of Three Intersecting Lines",
      "Another Peek Beyond the Point",
      "Arithmetic Expressions",
      "Connecting the Dots",
      "Constructions and Tilings",
      "Expressions Using Letter Numbers",
      "Finding Common Ground",
      "Finding the Unknown",
      "Geometric Twins",
      "Large Numbers Around Us",
      "Number Play",
      "Operations with Integers",
      "Parallel and Intersecting Lines",
      "Working with Fractions"
    ],
    "Science": [
      "Acids Bases and Salts",
      "Electric Current and its Effects",
      "Forests Our Lifeline",
      "Heat",
      "Light",
      "Motion and Time",
      "Nutrition in Animals",
      "Nutrition in Plants",
      "Physical and Chemical Changes",
      "Reproduction in Plants",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Wastewater Story"
    ]
  },
  "8": {
    "Mathematics": [
      "A Square and a Cube",
      "A Story of Numbers",
      "Algebra Play",
      "Area",
      "Exploring Some Geometric Themes",
      "Fractions in Disguise",
      "Number Play",
      "Power Play",
      "Proportional Reasoning 1",
      "Proportional Reasoning 2",
      "Quadrilaterals",
      "Tales By Dots and Lines",
      "The Baudhayana Pythagoras Theorem",
      "We Distribute Yet Things Multiply"
    ],
    "Science": [
      "Chemical Effects of Electric Current",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Crop Production and Management",
      "Force and Pressure",
      "Friction",
      "Light",
      "Microorganisms Friend and Foe",
      "Reaching the Age of Adolescence",
      "Reproduction in Animals",
      "Some Natural Phenomena",
      "Sound"
    ]
  },
  "9": {
    "Mathematics": [
      "Circles",
      "Coordinate Geometry",
      "Exploring Algebraic Identities",
      "Heron S Formula",
      "Introduction to Euclid S Geometry",
      "Linear Equations in Two Variables",
      "Lines and Angles",
      "Number Systems",
      "Polynomials",
      "Quadrilaterals",
      "Statistics",
      "Surface Areas and Volumes",
      "Triangles"
    ],
    "Science": [
      "Atomic Foundations of Matter",
      "Cell the Building Block of Life",
      "Describing Motion Around Us",
      "Earth As a System Energy Matter and Life",
      "Exploring Mixtures and Their Separation",
      "How Forces Affect Motion",
      "Journey Inside the Atom",
      "Patterns in Life Diversity and Classification",
      "Reproduction How Life Continues",
      "Sound Waves Characteristics and Applications",
      "Tissues in Action",
      "Work Energy and Simple Machines"
    ]
  },
  "10": {
    "Biology": [
      "Control and Coordination",
      "Heredity",
      "How Do Organisms Reproduce",
      "Life Processes",
      "Our Environment",
      "Sustainable Management of Natural Resources"
    ],
    "Chemistry": [
      "Acids Bases and Salts",
      "Carbon and its Compounds",
      "Chemical Reactions and Equations",
      "Metals and Non Metals"
    ],
    "Mathematics": [
      "Areas Related to Circles",
      "Arithmetic Progressions",
      "Circles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Pair of Linear Equations in Two Variables",
      "Polynomials",
      "Probability",
      "Quadratic Equations",
      "Real Numbers",
      "Some Applications of Trigonometry",
      "Statistics",
      "Surface Areas and Volumes",
      "Triangles"
    ],
    "Physics": [
      "Electricity",
      "Light Reflection and Refraction",
      "Magnetic Effects of Electric Current",
      "The Human Eye and the Colourful World"
    ]
  },
  "11": {
    "Biology": [
      "Anatomy of Flowering Plants",
      "Animal Kingdom",
      "Biomolecules",
      "Body Fluids and Circulation",
      "Breathing and Exchange of Gases",
      "Cell Cycle and Cell Division",
      "Cell the Unit of Life",
      "Chemical Coordination and Integration",
      "Excretory Products and Their Elimination",
      "Morphology of Flowering Plants",
      "Neural Control and Coordination",
      "Photosynthesis in Higher Plants",
      "Plant Kingdom",
      "Respiration in Plants"
    ],
    "Chemistry": [
      "Chemical Bonding and Molecular Structure",
      "Classification of Elements and Periodicity in Prop",
      "Equilibrium",
      "Hydrocarbons",
      "Organic Chemistry Some Basic Principles and Techni",
      "Redox Reactions",
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Thermodynamics"
    ],
    "Mathematics": [
      "Binomial Theorem",
      "Complex Numbers and Quadratic Equations",
      "Conic Sections",
      "Introduction to Three Dimensional Geometry",
      "Limits and Derivatives",
      "Linear Inequalities",
      "Permutations and Combinations",
      "Probability",
      "Relations and Functions",
      "Sequences and Series",
      "Sets",
      "Statistics",
      "Straight Lines",
      "Trigonometric Functions"
    ],
    "Physics": [
      "Gravitation",
      "Kinetic Theory",
      "Laws of Motion",
      "Mechanical Properties of Fluids",
      "Mechanical Properties of Solids",
      "Motion in a Plane",
      "Motion in a Straight Line",
      "Oscillations",
      "System of Particles and Rotational Motion",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Units and Measurements",
      "Waves",
      "Work Energy and Power"
    ]
  },
  "12": {
    "Biology": [
      "Biodiversity and Conservation",
      "Biotechnology Principles and Processes",
      "Biotechnology and its Applications",
      "Ecosystem",
      "Evolution",
      "Human Health and Disease",
      "Human Reproduction",
      "Microbes in Human Welfare",
      "Molecular Basis of Inheritance",
      "Organisms and Populations",
      "Principles of Inheritance and Variation",
      "Reproductive Health",
      "Sexual Reproduction in Flowering Plants"
    ],
    "Chemistry": [
      "Alcohols Phenols and Ethers",
      "Aldehydes Ketones and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Chemical Kinetics",
      "Coordination Compounds",
      "Electrochemistry",
      "Haloalkanes and Haloarenes",
      "Solutions",
      "The D and F Block Elements"
    ],
    "Mathematics": [
      "Application of Derivatives",
      "Application of Integrals",
      "Continuity and Differentiability",
      "Determinants",
      "Differential Equations",
      "Integrals",
      "Inverse Trigonometric Functions",
      "Linear Programming",
      "Matrices",
      "Probability",
      "Relations and Functions",
      "Three Dimensional Geometry",
      "Vector Algebra"
    ],
    "Physics": [
      "Alternating Current",
      "Atoms",
      "Current Electricity",
      "Dual Nature of Radiation and Matter",
      "Electric Charges and Fields",
      "Electromagnetic Induction",
      "Electromagnetic Waves",
      "Electrostatic Potential and Capacitance",
      "Magnetism and Matter",
      "Moving Charges and Magnetism",
      "Nuclei",
      "Ray Optics and Optical Instruments",
      "Semiconductor Electronics",
      "Wave Optics"
    ]
  }
};

/** Subjects available for a class label like "Class 6" or "6". */
export function subjectsForClass(classLabel: string): string[] {
  const cls = String(classLabel).replace(/[^0-9]/g, '');
  return Object.keys(HOMEWORK_CURRICULUM[cls] || {});
}

/** Chapters for a class + subject. Empty array if none (caller offers free text). */
export function chaptersFor(classLabel: string, subject: string): string[] {
  const cls = String(classLabel).replace(/[^0-9]/g, '');
  return (HOMEWORK_CURRICULUM[cls] && HOMEWORK_CURRICULUM[cls][subject]) || [];
}
