// AUTO-GENERATED by scripts/generate-maths-tables.mjs — do not edit by hand.
// Deterministic maths reference data for the /maths-tables cluster.

export interface MathRefFaq { q: string; a: string; }
export interface MathRef {
  slug: string;
  title: string;
  category: string;
  intro: string;
  columns: string[];
  rows: string[][];
  faqs: MathRefFaq[];
}

export const MATHS_TABLES: MathRef[] = [
  {
    "slug": "multiplication-table-of-2",
    "title": "Multiplication Table of 2",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 2 from 2×1 to 2×20 — learn and revise the 2 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "2 × 1",
        "2"
      ],
      [
        "2 × 2",
        "4"
      ],
      [
        "2 × 3",
        "6"
      ],
      [
        "2 × 4",
        "8"
      ],
      [
        "2 × 5",
        "10"
      ],
      [
        "2 × 6",
        "12"
      ],
      [
        "2 × 7",
        "14"
      ],
      [
        "2 × 8",
        "16"
      ],
      [
        "2 × 9",
        "18"
      ],
      [
        "2 × 10",
        "20"
      ],
      [
        "2 × 11",
        "22"
      ],
      [
        "2 × 12",
        "24"
      ],
      [
        "2 × 13",
        "26"
      ],
      [
        "2 × 14",
        "28"
      ],
      [
        "2 × 15",
        "30"
      ],
      [
        "2 × 16",
        "32"
      ],
      [
        "2 × 17",
        "34"
      ],
      [
        "2 × 18",
        "36"
      ],
      [
        "2 × 19",
        "38"
      ],
      [
        "2 × 20",
        "40"
      ]
    ],
    "faqs": [
      {
        "q": "What is 2 times 2?",
        "a": "2 × 2 = 4."
      },
      {
        "q": "How to learn the table of 2 fast?",
        "a": "Add 2 repeatedly: 2, 4, 6, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-3",
    "title": "Multiplication Table of 3",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 3 from 3×1 to 3×20 — learn and revise the 3 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "3 × 1",
        "3"
      ],
      [
        "3 × 2",
        "6"
      ],
      [
        "3 × 3",
        "9"
      ],
      [
        "3 × 4",
        "12"
      ],
      [
        "3 × 5",
        "15"
      ],
      [
        "3 × 6",
        "18"
      ],
      [
        "3 × 7",
        "21"
      ],
      [
        "3 × 8",
        "24"
      ],
      [
        "3 × 9",
        "27"
      ],
      [
        "3 × 10",
        "30"
      ],
      [
        "3 × 11",
        "33"
      ],
      [
        "3 × 12",
        "36"
      ],
      [
        "3 × 13",
        "39"
      ],
      [
        "3 × 14",
        "42"
      ],
      [
        "3 × 15",
        "45"
      ],
      [
        "3 × 16",
        "48"
      ],
      [
        "3 × 17",
        "51"
      ],
      [
        "3 × 18",
        "54"
      ],
      [
        "3 × 19",
        "57"
      ],
      [
        "3 × 20",
        "60"
      ]
    ],
    "faqs": [
      {
        "q": "What is 3 times 3?",
        "a": "3 × 3 = 9."
      },
      {
        "q": "How to learn the table of 3 fast?",
        "a": "Add 3 repeatedly: 3, 6, 9, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-4",
    "title": "Multiplication Table of 4",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 4 from 4×1 to 4×20 — learn and revise the 4 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "4 × 1",
        "4"
      ],
      [
        "4 × 2",
        "8"
      ],
      [
        "4 × 3",
        "12"
      ],
      [
        "4 × 4",
        "16"
      ],
      [
        "4 × 5",
        "20"
      ],
      [
        "4 × 6",
        "24"
      ],
      [
        "4 × 7",
        "28"
      ],
      [
        "4 × 8",
        "32"
      ],
      [
        "4 × 9",
        "36"
      ],
      [
        "4 × 10",
        "40"
      ],
      [
        "4 × 11",
        "44"
      ],
      [
        "4 × 12",
        "48"
      ],
      [
        "4 × 13",
        "52"
      ],
      [
        "4 × 14",
        "56"
      ],
      [
        "4 × 15",
        "60"
      ],
      [
        "4 × 16",
        "64"
      ],
      [
        "4 × 17",
        "68"
      ],
      [
        "4 × 18",
        "72"
      ],
      [
        "4 × 19",
        "76"
      ],
      [
        "4 × 20",
        "80"
      ]
    ],
    "faqs": [
      {
        "q": "What is 4 times 4?",
        "a": "4 × 4 = 16."
      },
      {
        "q": "How to learn the table of 4 fast?",
        "a": "Add 4 repeatedly: 4, 8, 12, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-5",
    "title": "Multiplication Table of 5",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 5 from 5×1 to 5×20 — learn and revise the 5 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "5 × 1",
        "5"
      ],
      [
        "5 × 2",
        "10"
      ],
      [
        "5 × 3",
        "15"
      ],
      [
        "5 × 4",
        "20"
      ],
      [
        "5 × 5",
        "25"
      ],
      [
        "5 × 6",
        "30"
      ],
      [
        "5 × 7",
        "35"
      ],
      [
        "5 × 8",
        "40"
      ],
      [
        "5 × 9",
        "45"
      ],
      [
        "5 × 10",
        "50"
      ],
      [
        "5 × 11",
        "55"
      ],
      [
        "5 × 12",
        "60"
      ],
      [
        "5 × 13",
        "65"
      ],
      [
        "5 × 14",
        "70"
      ],
      [
        "5 × 15",
        "75"
      ],
      [
        "5 × 16",
        "80"
      ],
      [
        "5 × 17",
        "85"
      ],
      [
        "5 × 18",
        "90"
      ],
      [
        "5 × 19",
        "95"
      ],
      [
        "5 × 20",
        "100"
      ]
    ],
    "faqs": [
      {
        "q": "What is 5 times 5?",
        "a": "5 × 5 = 25."
      },
      {
        "q": "How to learn the table of 5 fast?",
        "a": "Add 5 repeatedly: 5, 10, 15, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-6",
    "title": "Multiplication Table of 6",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 6 from 6×1 to 6×20 — learn and revise the 6 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "6 × 1",
        "6"
      ],
      [
        "6 × 2",
        "12"
      ],
      [
        "6 × 3",
        "18"
      ],
      [
        "6 × 4",
        "24"
      ],
      [
        "6 × 5",
        "30"
      ],
      [
        "6 × 6",
        "36"
      ],
      [
        "6 × 7",
        "42"
      ],
      [
        "6 × 8",
        "48"
      ],
      [
        "6 × 9",
        "54"
      ],
      [
        "6 × 10",
        "60"
      ],
      [
        "6 × 11",
        "66"
      ],
      [
        "6 × 12",
        "72"
      ],
      [
        "6 × 13",
        "78"
      ],
      [
        "6 × 14",
        "84"
      ],
      [
        "6 × 15",
        "90"
      ],
      [
        "6 × 16",
        "96"
      ],
      [
        "6 × 17",
        "102"
      ],
      [
        "6 × 18",
        "108"
      ],
      [
        "6 × 19",
        "114"
      ],
      [
        "6 × 20",
        "120"
      ]
    ],
    "faqs": [
      {
        "q": "What is 6 times 6?",
        "a": "6 × 6 = 36."
      },
      {
        "q": "How to learn the table of 6 fast?",
        "a": "Add 6 repeatedly: 6, 12, 18, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-7",
    "title": "Multiplication Table of 7",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 7 from 7×1 to 7×20 — learn and revise the 7 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "7 × 1",
        "7"
      ],
      [
        "7 × 2",
        "14"
      ],
      [
        "7 × 3",
        "21"
      ],
      [
        "7 × 4",
        "28"
      ],
      [
        "7 × 5",
        "35"
      ],
      [
        "7 × 6",
        "42"
      ],
      [
        "7 × 7",
        "49"
      ],
      [
        "7 × 8",
        "56"
      ],
      [
        "7 × 9",
        "63"
      ],
      [
        "7 × 10",
        "70"
      ],
      [
        "7 × 11",
        "77"
      ],
      [
        "7 × 12",
        "84"
      ],
      [
        "7 × 13",
        "91"
      ],
      [
        "7 × 14",
        "98"
      ],
      [
        "7 × 15",
        "105"
      ],
      [
        "7 × 16",
        "112"
      ],
      [
        "7 × 17",
        "119"
      ],
      [
        "7 × 18",
        "126"
      ],
      [
        "7 × 19",
        "133"
      ],
      [
        "7 × 20",
        "140"
      ]
    ],
    "faqs": [
      {
        "q": "What is 7 times 7?",
        "a": "7 × 7 = 49."
      },
      {
        "q": "How to learn the table of 7 fast?",
        "a": "Add 7 repeatedly: 7, 14, 21, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-8",
    "title": "Multiplication Table of 8",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 8 from 8×1 to 8×20 — learn and revise the 8 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "8 × 1",
        "8"
      ],
      [
        "8 × 2",
        "16"
      ],
      [
        "8 × 3",
        "24"
      ],
      [
        "8 × 4",
        "32"
      ],
      [
        "8 × 5",
        "40"
      ],
      [
        "8 × 6",
        "48"
      ],
      [
        "8 × 7",
        "56"
      ],
      [
        "8 × 8",
        "64"
      ],
      [
        "8 × 9",
        "72"
      ],
      [
        "8 × 10",
        "80"
      ],
      [
        "8 × 11",
        "88"
      ],
      [
        "8 × 12",
        "96"
      ],
      [
        "8 × 13",
        "104"
      ],
      [
        "8 × 14",
        "112"
      ],
      [
        "8 × 15",
        "120"
      ],
      [
        "8 × 16",
        "128"
      ],
      [
        "8 × 17",
        "136"
      ],
      [
        "8 × 18",
        "144"
      ],
      [
        "8 × 19",
        "152"
      ],
      [
        "8 × 20",
        "160"
      ]
    ],
    "faqs": [
      {
        "q": "What is 8 times 8?",
        "a": "8 × 8 = 64."
      },
      {
        "q": "How to learn the table of 8 fast?",
        "a": "Add 8 repeatedly: 8, 16, 24, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-9",
    "title": "Multiplication Table of 9",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 9 from 9×1 to 9×20 — learn and revise the 9 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "9 × 1",
        "9"
      ],
      [
        "9 × 2",
        "18"
      ],
      [
        "9 × 3",
        "27"
      ],
      [
        "9 × 4",
        "36"
      ],
      [
        "9 × 5",
        "45"
      ],
      [
        "9 × 6",
        "54"
      ],
      [
        "9 × 7",
        "63"
      ],
      [
        "9 × 8",
        "72"
      ],
      [
        "9 × 9",
        "81"
      ],
      [
        "9 × 10",
        "90"
      ],
      [
        "9 × 11",
        "99"
      ],
      [
        "9 × 12",
        "108"
      ],
      [
        "9 × 13",
        "117"
      ],
      [
        "9 × 14",
        "126"
      ],
      [
        "9 × 15",
        "135"
      ],
      [
        "9 × 16",
        "144"
      ],
      [
        "9 × 17",
        "153"
      ],
      [
        "9 × 18",
        "162"
      ],
      [
        "9 × 19",
        "171"
      ],
      [
        "9 × 20",
        "180"
      ]
    ],
    "faqs": [
      {
        "q": "What is 9 times 9?",
        "a": "9 × 9 = 81."
      },
      {
        "q": "How to learn the table of 9 fast?",
        "a": "Add 9 repeatedly: 9, 18, 27, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-10",
    "title": "Multiplication Table of 10",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 10 from 10×1 to 10×20 — learn and revise the 10 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "10 × 1",
        "10"
      ],
      [
        "10 × 2",
        "20"
      ],
      [
        "10 × 3",
        "30"
      ],
      [
        "10 × 4",
        "40"
      ],
      [
        "10 × 5",
        "50"
      ],
      [
        "10 × 6",
        "60"
      ],
      [
        "10 × 7",
        "70"
      ],
      [
        "10 × 8",
        "80"
      ],
      [
        "10 × 9",
        "90"
      ],
      [
        "10 × 10",
        "100"
      ],
      [
        "10 × 11",
        "110"
      ],
      [
        "10 × 12",
        "120"
      ],
      [
        "10 × 13",
        "130"
      ],
      [
        "10 × 14",
        "140"
      ],
      [
        "10 × 15",
        "150"
      ],
      [
        "10 × 16",
        "160"
      ],
      [
        "10 × 17",
        "170"
      ],
      [
        "10 × 18",
        "180"
      ],
      [
        "10 × 19",
        "190"
      ],
      [
        "10 × 20",
        "200"
      ]
    ],
    "faqs": [
      {
        "q": "What is 10 times 10?",
        "a": "10 × 10 = 100."
      },
      {
        "q": "How to learn the table of 10 fast?",
        "a": "Add 10 repeatedly: 10, 20, 30, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-11",
    "title": "Multiplication Table of 11",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 11 from 11×1 to 11×20 — learn and revise the 11 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "11 × 1",
        "11"
      ],
      [
        "11 × 2",
        "22"
      ],
      [
        "11 × 3",
        "33"
      ],
      [
        "11 × 4",
        "44"
      ],
      [
        "11 × 5",
        "55"
      ],
      [
        "11 × 6",
        "66"
      ],
      [
        "11 × 7",
        "77"
      ],
      [
        "11 × 8",
        "88"
      ],
      [
        "11 × 9",
        "99"
      ],
      [
        "11 × 10",
        "110"
      ],
      [
        "11 × 11",
        "121"
      ],
      [
        "11 × 12",
        "132"
      ],
      [
        "11 × 13",
        "143"
      ],
      [
        "11 × 14",
        "154"
      ],
      [
        "11 × 15",
        "165"
      ],
      [
        "11 × 16",
        "176"
      ],
      [
        "11 × 17",
        "187"
      ],
      [
        "11 × 18",
        "198"
      ],
      [
        "11 × 19",
        "209"
      ],
      [
        "11 × 20",
        "220"
      ]
    ],
    "faqs": [
      {
        "q": "What is 11 times 11?",
        "a": "11 × 11 = 121."
      },
      {
        "q": "How to learn the table of 11 fast?",
        "a": "Add 11 repeatedly: 11, 22, 33, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-12",
    "title": "Multiplication Table of 12",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 12 from 12×1 to 12×20 — learn and revise the 12 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "12 × 1",
        "12"
      ],
      [
        "12 × 2",
        "24"
      ],
      [
        "12 × 3",
        "36"
      ],
      [
        "12 × 4",
        "48"
      ],
      [
        "12 × 5",
        "60"
      ],
      [
        "12 × 6",
        "72"
      ],
      [
        "12 × 7",
        "84"
      ],
      [
        "12 × 8",
        "96"
      ],
      [
        "12 × 9",
        "108"
      ],
      [
        "12 × 10",
        "120"
      ],
      [
        "12 × 11",
        "132"
      ],
      [
        "12 × 12",
        "144"
      ],
      [
        "12 × 13",
        "156"
      ],
      [
        "12 × 14",
        "168"
      ],
      [
        "12 × 15",
        "180"
      ],
      [
        "12 × 16",
        "192"
      ],
      [
        "12 × 17",
        "204"
      ],
      [
        "12 × 18",
        "216"
      ],
      [
        "12 × 19",
        "228"
      ],
      [
        "12 × 20",
        "240"
      ]
    ],
    "faqs": [
      {
        "q": "What is 12 times 12?",
        "a": "12 × 12 = 144."
      },
      {
        "q": "How to learn the table of 12 fast?",
        "a": "Add 12 repeatedly: 12, 24, 36, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-13",
    "title": "Multiplication Table of 13",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 13 from 13×1 to 13×20 — learn and revise the 13 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "13 × 1",
        "13"
      ],
      [
        "13 × 2",
        "26"
      ],
      [
        "13 × 3",
        "39"
      ],
      [
        "13 × 4",
        "52"
      ],
      [
        "13 × 5",
        "65"
      ],
      [
        "13 × 6",
        "78"
      ],
      [
        "13 × 7",
        "91"
      ],
      [
        "13 × 8",
        "104"
      ],
      [
        "13 × 9",
        "117"
      ],
      [
        "13 × 10",
        "130"
      ],
      [
        "13 × 11",
        "143"
      ],
      [
        "13 × 12",
        "156"
      ],
      [
        "13 × 13",
        "169"
      ],
      [
        "13 × 14",
        "182"
      ],
      [
        "13 × 15",
        "195"
      ],
      [
        "13 × 16",
        "208"
      ],
      [
        "13 × 17",
        "221"
      ],
      [
        "13 × 18",
        "234"
      ],
      [
        "13 × 19",
        "247"
      ],
      [
        "13 × 20",
        "260"
      ]
    ],
    "faqs": [
      {
        "q": "What is 13 times 13?",
        "a": "13 × 13 = 169."
      },
      {
        "q": "How to learn the table of 13 fast?",
        "a": "Add 13 repeatedly: 13, 26, 39, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-14",
    "title": "Multiplication Table of 14",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 14 from 14×1 to 14×20 — learn and revise the 14 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "14 × 1",
        "14"
      ],
      [
        "14 × 2",
        "28"
      ],
      [
        "14 × 3",
        "42"
      ],
      [
        "14 × 4",
        "56"
      ],
      [
        "14 × 5",
        "70"
      ],
      [
        "14 × 6",
        "84"
      ],
      [
        "14 × 7",
        "98"
      ],
      [
        "14 × 8",
        "112"
      ],
      [
        "14 × 9",
        "126"
      ],
      [
        "14 × 10",
        "140"
      ],
      [
        "14 × 11",
        "154"
      ],
      [
        "14 × 12",
        "168"
      ],
      [
        "14 × 13",
        "182"
      ],
      [
        "14 × 14",
        "196"
      ],
      [
        "14 × 15",
        "210"
      ],
      [
        "14 × 16",
        "224"
      ],
      [
        "14 × 17",
        "238"
      ],
      [
        "14 × 18",
        "252"
      ],
      [
        "14 × 19",
        "266"
      ],
      [
        "14 × 20",
        "280"
      ]
    ],
    "faqs": [
      {
        "q": "What is 14 times 14?",
        "a": "14 × 14 = 196."
      },
      {
        "q": "How to learn the table of 14 fast?",
        "a": "Add 14 repeatedly: 14, 28, 42, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-15",
    "title": "Multiplication Table of 15",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 15 from 15×1 to 15×20 — learn and revise the 15 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "15 × 1",
        "15"
      ],
      [
        "15 × 2",
        "30"
      ],
      [
        "15 × 3",
        "45"
      ],
      [
        "15 × 4",
        "60"
      ],
      [
        "15 × 5",
        "75"
      ],
      [
        "15 × 6",
        "90"
      ],
      [
        "15 × 7",
        "105"
      ],
      [
        "15 × 8",
        "120"
      ],
      [
        "15 × 9",
        "135"
      ],
      [
        "15 × 10",
        "150"
      ],
      [
        "15 × 11",
        "165"
      ],
      [
        "15 × 12",
        "180"
      ],
      [
        "15 × 13",
        "195"
      ],
      [
        "15 × 14",
        "210"
      ],
      [
        "15 × 15",
        "225"
      ],
      [
        "15 × 16",
        "240"
      ],
      [
        "15 × 17",
        "255"
      ],
      [
        "15 × 18",
        "270"
      ],
      [
        "15 × 19",
        "285"
      ],
      [
        "15 × 20",
        "300"
      ]
    ],
    "faqs": [
      {
        "q": "What is 15 times 15?",
        "a": "15 × 15 = 225."
      },
      {
        "q": "How to learn the table of 15 fast?",
        "a": "Add 15 repeatedly: 15, 30, 45, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-16",
    "title": "Multiplication Table of 16",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 16 from 16×1 to 16×20 — learn and revise the 16 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "16 × 1",
        "16"
      ],
      [
        "16 × 2",
        "32"
      ],
      [
        "16 × 3",
        "48"
      ],
      [
        "16 × 4",
        "64"
      ],
      [
        "16 × 5",
        "80"
      ],
      [
        "16 × 6",
        "96"
      ],
      [
        "16 × 7",
        "112"
      ],
      [
        "16 × 8",
        "128"
      ],
      [
        "16 × 9",
        "144"
      ],
      [
        "16 × 10",
        "160"
      ],
      [
        "16 × 11",
        "176"
      ],
      [
        "16 × 12",
        "192"
      ],
      [
        "16 × 13",
        "208"
      ],
      [
        "16 × 14",
        "224"
      ],
      [
        "16 × 15",
        "240"
      ],
      [
        "16 × 16",
        "256"
      ],
      [
        "16 × 17",
        "272"
      ],
      [
        "16 × 18",
        "288"
      ],
      [
        "16 × 19",
        "304"
      ],
      [
        "16 × 20",
        "320"
      ]
    ],
    "faqs": [
      {
        "q": "What is 16 times 16?",
        "a": "16 × 16 = 256."
      },
      {
        "q": "How to learn the table of 16 fast?",
        "a": "Add 16 repeatedly: 16, 32, 48, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-17",
    "title": "Multiplication Table of 17",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 17 from 17×1 to 17×20 — learn and revise the 17 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "17 × 1",
        "17"
      ],
      [
        "17 × 2",
        "34"
      ],
      [
        "17 × 3",
        "51"
      ],
      [
        "17 × 4",
        "68"
      ],
      [
        "17 × 5",
        "85"
      ],
      [
        "17 × 6",
        "102"
      ],
      [
        "17 × 7",
        "119"
      ],
      [
        "17 × 8",
        "136"
      ],
      [
        "17 × 9",
        "153"
      ],
      [
        "17 × 10",
        "170"
      ],
      [
        "17 × 11",
        "187"
      ],
      [
        "17 × 12",
        "204"
      ],
      [
        "17 × 13",
        "221"
      ],
      [
        "17 × 14",
        "238"
      ],
      [
        "17 × 15",
        "255"
      ],
      [
        "17 × 16",
        "272"
      ],
      [
        "17 × 17",
        "289"
      ],
      [
        "17 × 18",
        "306"
      ],
      [
        "17 × 19",
        "323"
      ],
      [
        "17 × 20",
        "340"
      ]
    ],
    "faqs": [
      {
        "q": "What is 17 times 17?",
        "a": "17 × 17 = 289."
      },
      {
        "q": "How to learn the table of 17 fast?",
        "a": "Add 17 repeatedly: 17, 34, 51, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-18",
    "title": "Multiplication Table of 18",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 18 from 18×1 to 18×20 — learn and revise the 18 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "18 × 1",
        "18"
      ],
      [
        "18 × 2",
        "36"
      ],
      [
        "18 × 3",
        "54"
      ],
      [
        "18 × 4",
        "72"
      ],
      [
        "18 × 5",
        "90"
      ],
      [
        "18 × 6",
        "108"
      ],
      [
        "18 × 7",
        "126"
      ],
      [
        "18 × 8",
        "144"
      ],
      [
        "18 × 9",
        "162"
      ],
      [
        "18 × 10",
        "180"
      ],
      [
        "18 × 11",
        "198"
      ],
      [
        "18 × 12",
        "216"
      ],
      [
        "18 × 13",
        "234"
      ],
      [
        "18 × 14",
        "252"
      ],
      [
        "18 × 15",
        "270"
      ],
      [
        "18 × 16",
        "288"
      ],
      [
        "18 × 17",
        "306"
      ],
      [
        "18 × 18",
        "324"
      ],
      [
        "18 × 19",
        "342"
      ],
      [
        "18 × 20",
        "360"
      ]
    ],
    "faqs": [
      {
        "q": "What is 18 times 18?",
        "a": "18 × 18 = 324."
      },
      {
        "q": "How to learn the table of 18 fast?",
        "a": "Add 18 repeatedly: 18, 36, 54, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-19",
    "title": "Multiplication Table of 19",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 19 from 19×1 to 19×20 — learn and revise the 19 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "19 × 1",
        "19"
      ],
      [
        "19 × 2",
        "38"
      ],
      [
        "19 × 3",
        "57"
      ],
      [
        "19 × 4",
        "76"
      ],
      [
        "19 × 5",
        "95"
      ],
      [
        "19 × 6",
        "114"
      ],
      [
        "19 × 7",
        "133"
      ],
      [
        "19 × 8",
        "152"
      ],
      [
        "19 × 9",
        "171"
      ],
      [
        "19 × 10",
        "190"
      ],
      [
        "19 × 11",
        "209"
      ],
      [
        "19 × 12",
        "228"
      ],
      [
        "19 × 13",
        "247"
      ],
      [
        "19 × 14",
        "266"
      ],
      [
        "19 × 15",
        "285"
      ],
      [
        "19 × 16",
        "304"
      ],
      [
        "19 × 17",
        "323"
      ],
      [
        "19 × 18",
        "342"
      ],
      [
        "19 × 19",
        "361"
      ],
      [
        "19 × 20",
        "380"
      ]
    ],
    "faqs": [
      {
        "q": "What is 19 times 19?",
        "a": "19 × 19 = 361."
      },
      {
        "q": "How to learn the table of 19 fast?",
        "a": "Add 19 repeatedly: 19, 38, 57, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "multiplication-table-of-20",
    "title": "Multiplication Table of 20",
    "category": "Multiplication Tables",
    "intro": "The multiplication table of 20 from 20×1 to 20×20 — learn and revise the 20 times table for fast mental maths.",
    "columns": [
      "Multiplication",
      "Result"
    ],
    "rows": [
      [
        "20 × 1",
        "20"
      ],
      [
        "20 × 2",
        "40"
      ],
      [
        "20 × 3",
        "60"
      ],
      [
        "20 × 4",
        "80"
      ],
      [
        "20 × 5",
        "100"
      ],
      [
        "20 × 6",
        "120"
      ],
      [
        "20 × 7",
        "140"
      ],
      [
        "20 × 8",
        "160"
      ],
      [
        "20 × 9",
        "180"
      ],
      [
        "20 × 10",
        "200"
      ],
      [
        "20 × 11",
        "220"
      ],
      [
        "20 × 12",
        "240"
      ],
      [
        "20 × 13",
        "260"
      ],
      [
        "20 × 14",
        "280"
      ],
      [
        "20 × 15",
        "300"
      ],
      [
        "20 × 16",
        "320"
      ],
      [
        "20 × 17",
        "340"
      ],
      [
        "20 × 18",
        "360"
      ],
      [
        "20 × 19",
        "380"
      ],
      [
        "20 × 20",
        "400"
      ]
    ],
    "faqs": [
      {
        "q": "What is 20 times 20?",
        "a": "20 × 20 = 400."
      },
      {
        "q": "How to learn the table of 20 fast?",
        "a": "Add 20 repeatedly: 20, 40, 60, and so on. Practising daily for a few minutes helps you memorise it quickly."
      }
    ]
  },
  {
    "slug": "squares-1-to-50",
    "title": "Squares from 1 to 50",
    "category": "Squares & Cubes",
    "intro": "List of square numbers from 1 to 50 (n²) — useful for fast calculation, quadratic equations and competitive exams.",
    "columns": [
      "Number",
      "Square"
    ],
    "rows": [
      [
        "1",
        "1"
      ],
      [
        "2",
        "4"
      ],
      [
        "3",
        "9"
      ],
      [
        "4",
        "16"
      ],
      [
        "5",
        "25"
      ],
      [
        "6",
        "36"
      ],
      [
        "7",
        "49"
      ],
      [
        "8",
        "64"
      ],
      [
        "9",
        "81"
      ],
      [
        "10",
        "100"
      ],
      [
        "11",
        "121"
      ],
      [
        "12",
        "144"
      ],
      [
        "13",
        "169"
      ],
      [
        "14",
        "196"
      ],
      [
        "15",
        "225"
      ],
      [
        "16",
        "256"
      ],
      [
        "17",
        "289"
      ],
      [
        "18",
        "324"
      ],
      [
        "19",
        "361"
      ],
      [
        "20",
        "400"
      ],
      [
        "21",
        "441"
      ],
      [
        "22",
        "484"
      ],
      [
        "23",
        "529"
      ],
      [
        "24",
        "576"
      ],
      [
        "25",
        "625"
      ],
      [
        "26",
        "676"
      ],
      [
        "27",
        "729"
      ],
      [
        "28",
        "784"
      ],
      [
        "29",
        "841"
      ],
      [
        "30",
        "900"
      ],
      [
        "31",
        "961"
      ],
      [
        "32",
        "1024"
      ],
      [
        "33",
        "1089"
      ],
      [
        "34",
        "1156"
      ],
      [
        "35",
        "1225"
      ],
      [
        "36",
        "1296"
      ],
      [
        "37",
        "1369"
      ],
      [
        "38",
        "1444"
      ],
      [
        "39",
        "1521"
      ],
      [
        "40",
        "1600"
      ],
      [
        "41",
        "1681"
      ],
      [
        "42",
        "1764"
      ],
      [
        "43",
        "1849"
      ],
      [
        "44",
        "1936"
      ],
      [
        "45",
        "2025"
      ],
      [
        "46",
        "2116"
      ],
      [
        "47",
        "2209"
      ],
      [
        "48",
        "2304"
      ],
      [
        "49",
        "2401"
      ],
      [
        "50",
        "2500"
      ]
    ],
    "faqs": [
      {
        "q": "What is the square of 25?",
        "a": "25² = 625."
      },
      {
        "q": "What is a perfect square?",
        "a": "A perfect square is a number that is the square of an integer, like 1, 4, 9, 16, 25."
      }
    ]
  },
  {
    "slug": "cubes-1-to-30",
    "title": "Cubes from 1 to 30",
    "category": "Squares & Cubes",
    "intro": "List of cube numbers from 1 to 30 (n³) — handy for fast calculation and competitive exams.",
    "columns": [
      "Number",
      "Cube"
    ],
    "rows": [
      [
        "1",
        "1"
      ],
      [
        "2",
        "8"
      ],
      [
        "3",
        "27"
      ],
      [
        "4",
        "64"
      ],
      [
        "5",
        "125"
      ],
      [
        "6",
        "216"
      ],
      [
        "7",
        "343"
      ],
      [
        "8",
        "512"
      ],
      [
        "9",
        "729"
      ],
      [
        "10",
        "1000"
      ],
      [
        "11",
        "1331"
      ],
      [
        "12",
        "1728"
      ],
      [
        "13",
        "2197"
      ],
      [
        "14",
        "2744"
      ],
      [
        "15",
        "3375"
      ],
      [
        "16",
        "4096"
      ],
      [
        "17",
        "4913"
      ],
      [
        "18",
        "5832"
      ],
      [
        "19",
        "6859"
      ],
      [
        "20",
        "8000"
      ],
      [
        "21",
        "9261"
      ],
      [
        "22",
        "10648"
      ],
      [
        "23",
        "12167"
      ],
      [
        "24",
        "13824"
      ],
      [
        "25",
        "15625"
      ],
      [
        "26",
        "17576"
      ],
      [
        "27",
        "19683"
      ],
      [
        "28",
        "21952"
      ],
      [
        "29",
        "24389"
      ],
      [
        "30",
        "27000"
      ]
    ],
    "faqs": [
      {
        "q": "What is the cube of 12?",
        "a": "12³ = 1728."
      },
      {
        "q": "What is a perfect cube?",
        "a": "A perfect cube is a number that is the cube of an integer, like 1, 8, 27, 64."
      }
    ]
  },
  {
    "slug": "square-roots-1-to-30",
    "title": "Square Roots from 1 to 30",
    "category": "Squares & Cubes",
    "intro": "Square root values (√n) from 1 to 30, rounded to 3 decimals — quick reference for maths and physics calculations.",
    "columns": [
      "Number",
      "Square Root (√n)"
    ],
    "rows": [
      [
        "1",
        "1.000"
      ],
      [
        "2",
        "1.414"
      ],
      [
        "3",
        "1.732"
      ],
      [
        "4",
        "2.000"
      ],
      [
        "5",
        "2.236"
      ],
      [
        "6",
        "2.449"
      ],
      [
        "7",
        "2.646"
      ],
      [
        "8",
        "2.828"
      ],
      [
        "9",
        "3.000"
      ],
      [
        "10",
        "3.162"
      ],
      [
        "11",
        "3.317"
      ],
      [
        "12",
        "3.464"
      ],
      [
        "13",
        "3.606"
      ],
      [
        "14",
        "3.742"
      ],
      [
        "15",
        "3.873"
      ],
      [
        "16",
        "4.000"
      ],
      [
        "17",
        "4.123"
      ],
      [
        "18",
        "4.243"
      ],
      [
        "19",
        "4.359"
      ],
      [
        "20",
        "4.472"
      ],
      [
        "21",
        "4.583"
      ],
      [
        "22",
        "4.690"
      ],
      [
        "23",
        "4.796"
      ],
      [
        "24",
        "4.899"
      ],
      [
        "25",
        "5.000"
      ],
      [
        "26",
        "5.099"
      ],
      [
        "27",
        "5.196"
      ],
      [
        "28",
        "5.292"
      ],
      [
        "29",
        "5.385"
      ],
      [
        "30",
        "5.477"
      ]
    ],
    "faqs": [
      {
        "q": "What is the square root of 2?",
        "a": "√2 ≈ 1.414."
      },
      {
        "q": "Which numbers have whole square roots?",
        "a": "Only perfect squares (1, 4, 9, 16, 25, ...) have whole-number square roots."
      }
    ]
  },
  {
    "slug": "cube-roots-1-to-30",
    "title": "Cube Roots from 1 to 30",
    "category": "Squares & Cubes",
    "intro": "Cube root values (∛n) from 1 to 30, rounded to 3 decimals — quick reference for fast calculation.",
    "columns": [
      "Number",
      "Cube Root (∛n)"
    ],
    "rows": [
      [
        "1",
        "1.000"
      ],
      [
        "2",
        "1.260"
      ],
      [
        "3",
        "1.442"
      ],
      [
        "4",
        "1.587"
      ],
      [
        "5",
        "1.710"
      ],
      [
        "6",
        "1.817"
      ],
      [
        "7",
        "1.913"
      ],
      [
        "8",
        "2.000"
      ],
      [
        "9",
        "2.080"
      ],
      [
        "10",
        "2.154"
      ],
      [
        "11",
        "2.224"
      ],
      [
        "12",
        "2.289"
      ],
      [
        "13",
        "2.351"
      ],
      [
        "14",
        "2.410"
      ],
      [
        "15",
        "2.466"
      ],
      [
        "16",
        "2.520"
      ],
      [
        "17",
        "2.571"
      ],
      [
        "18",
        "2.621"
      ],
      [
        "19",
        "2.668"
      ],
      [
        "20",
        "2.714"
      ],
      [
        "21",
        "2.759"
      ],
      [
        "22",
        "2.802"
      ],
      [
        "23",
        "2.844"
      ],
      [
        "24",
        "2.884"
      ],
      [
        "25",
        "2.924"
      ],
      [
        "26",
        "2.962"
      ],
      [
        "27",
        "3.000"
      ],
      [
        "28",
        "3.037"
      ],
      [
        "29",
        "3.072"
      ],
      [
        "30",
        "3.107"
      ]
    ],
    "faqs": [
      {
        "q": "What is the cube root of 27?",
        "a": "∛27 = 3."
      },
      {
        "q": "What is a cube root?",
        "a": "The cube root of a number x is the value that, when multiplied by itself three times, gives x."
      }
    ]
  },
  {
    "slug": "prime-numbers-1-to-100",
    "title": "Prime Numbers from 1 to 100",
    "category": "Number Lists",
    "intro": "There are 25 prime numbers between 1 and 100. A prime number has exactly two factors — 1 and itself.",
    "columns": [
      "#",
      "Prime Number"
    ],
    "rows": [
      [
        "1",
        "2"
      ],
      [
        "2",
        "3"
      ],
      [
        "3",
        "5"
      ],
      [
        "4",
        "7"
      ],
      [
        "5",
        "11"
      ],
      [
        "6",
        "13"
      ],
      [
        "7",
        "17"
      ],
      [
        "8",
        "19"
      ],
      [
        "9",
        "23"
      ],
      [
        "10",
        "29"
      ],
      [
        "11",
        "31"
      ],
      [
        "12",
        "37"
      ],
      [
        "13",
        "41"
      ],
      [
        "14",
        "43"
      ],
      [
        "15",
        "47"
      ],
      [
        "16",
        "53"
      ],
      [
        "17",
        "59"
      ],
      [
        "18",
        "61"
      ],
      [
        "19",
        "67"
      ],
      [
        "20",
        "71"
      ],
      [
        "21",
        "73"
      ],
      [
        "22",
        "79"
      ],
      [
        "23",
        "83"
      ],
      [
        "24",
        "89"
      ],
      [
        "25",
        "97"
      ]
    ],
    "faqs": [
      {
        "q": "How many prime numbers are there from 1 to 100?",
        "a": "There are 25 prime numbers between 1 and 100."
      },
      {
        "q": "Is 1 a prime number?",
        "a": "No. 1 has only one factor (itself), so it is neither prime nor composite. The smallest prime number is 2."
      }
    ]
  },
  {
    "slug": "roman-numerals-1-to-100",
    "title": "Roman Numerals from 1 to 100",
    "category": "Number Lists",
    "intro": "Roman numerals from 1 to 100 (I, II, III … C) with their values — a complete chart for students.",
    "columns": [
      "Number",
      "Roman Numeral"
    ],
    "rows": [
      [
        "1",
        "I"
      ],
      [
        "2",
        "II"
      ],
      [
        "3",
        "III"
      ],
      [
        "4",
        "IV"
      ],
      [
        "5",
        "V"
      ],
      [
        "6",
        "VI"
      ],
      [
        "7",
        "VII"
      ],
      [
        "8",
        "VIII"
      ],
      [
        "9",
        "IX"
      ],
      [
        "10",
        "X"
      ],
      [
        "11",
        "XI"
      ],
      [
        "12",
        "XII"
      ],
      [
        "13",
        "XIII"
      ],
      [
        "14",
        "XIV"
      ],
      [
        "15",
        "XV"
      ],
      [
        "16",
        "XVI"
      ],
      [
        "17",
        "XVII"
      ],
      [
        "18",
        "XVIII"
      ],
      [
        "19",
        "XIX"
      ],
      [
        "20",
        "XX"
      ],
      [
        "21",
        "XXI"
      ],
      [
        "22",
        "XXII"
      ],
      [
        "23",
        "XXIII"
      ],
      [
        "24",
        "XXIV"
      ],
      [
        "25",
        "XXV"
      ],
      [
        "26",
        "XXVI"
      ],
      [
        "27",
        "XXVII"
      ],
      [
        "28",
        "XXVIII"
      ],
      [
        "29",
        "XXIX"
      ],
      [
        "30",
        "XXX"
      ],
      [
        "31",
        "XXXI"
      ],
      [
        "32",
        "XXXII"
      ],
      [
        "33",
        "XXXIII"
      ],
      [
        "34",
        "XXXIV"
      ],
      [
        "35",
        "XXXV"
      ],
      [
        "36",
        "XXXVI"
      ],
      [
        "37",
        "XXXVII"
      ],
      [
        "38",
        "XXXVIII"
      ],
      [
        "39",
        "XXXIX"
      ],
      [
        "40",
        "XL"
      ],
      [
        "41",
        "XLI"
      ],
      [
        "42",
        "XLII"
      ],
      [
        "43",
        "XLIII"
      ],
      [
        "44",
        "XLIV"
      ],
      [
        "45",
        "XLV"
      ],
      [
        "46",
        "XLVI"
      ],
      [
        "47",
        "XLVII"
      ],
      [
        "48",
        "XLVIII"
      ],
      [
        "49",
        "XLIX"
      ],
      [
        "50",
        "L"
      ],
      [
        "51",
        "LI"
      ],
      [
        "52",
        "LII"
      ],
      [
        "53",
        "LIII"
      ],
      [
        "54",
        "LIV"
      ],
      [
        "55",
        "LV"
      ],
      [
        "56",
        "LVI"
      ],
      [
        "57",
        "LVII"
      ],
      [
        "58",
        "LVIII"
      ],
      [
        "59",
        "LIX"
      ],
      [
        "60",
        "LX"
      ],
      [
        "61",
        "LXI"
      ],
      [
        "62",
        "LXII"
      ],
      [
        "63",
        "LXIII"
      ],
      [
        "64",
        "LXIV"
      ],
      [
        "65",
        "LXV"
      ],
      [
        "66",
        "LXVI"
      ],
      [
        "67",
        "LXVII"
      ],
      [
        "68",
        "LXVIII"
      ],
      [
        "69",
        "LXIX"
      ],
      [
        "70",
        "LXX"
      ],
      [
        "71",
        "LXXI"
      ],
      [
        "72",
        "LXXII"
      ],
      [
        "73",
        "LXXIII"
      ],
      [
        "74",
        "LXXIV"
      ],
      [
        "75",
        "LXXV"
      ],
      [
        "76",
        "LXXVI"
      ],
      [
        "77",
        "LXXVII"
      ],
      [
        "78",
        "LXXVIII"
      ],
      [
        "79",
        "LXXIX"
      ],
      [
        "80",
        "LXXX"
      ],
      [
        "81",
        "LXXXI"
      ],
      [
        "82",
        "LXXXII"
      ],
      [
        "83",
        "LXXXIII"
      ],
      [
        "84",
        "LXXXIV"
      ],
      [
        "85",
        "LXXXV"
      ],
      [
        "86",
        "LXXXVI"
      ],
      [
        "87",
        "LXXXVII"
      ],
      [
        "88",
        "LXXXVIII"
      ],
      [
        "89",
        "LXXXIX"
      ],
      [
        "90",
        "XC"
      ],
      [
        "91",
        "XCI"
      ],
      [
        "92",
        "XCII"
      ],
      [
        "93",
        "XCIII"
      ],
      [
        "94",
        "XCIV"
      ],
      [
        "95",
        "XCV"
      ],
      [
        "96",
        "XCVI"
      ],
      [
        "97",
        "XCVII"
      ],
      [
        "98",
        "XCVIII"
      ],
      [
        "99",
        "XCIX"
      ],
      [
        "100",
        "C"
      ]
    ],
    "faqs": [
      {
        "q": "How do you write 50 in Roman numerals?",
        "a": "50 is written as L."
      },
      {
        "q": "What is the Roman numeral for 100?",
        "a": "100 is written as C."
      }
    ]
  },
  {
    "slug": "even-numbers-1-to-100",
    "title": "Even Numbers from 1 to 100",
    "category": "Number Lists",
    "intro": "List of all even numbers from 1 to 100. An even number is divisible by 2.",
    "columns": [
      "#",
      "Even Number"
    ],
    "rows": [
      [
        "1",
        "2"
      ],
      [
        "2",
        "4"
      ],
      [
        "3",
        "6"
      ],
      [
        "4",
        "8"
      ],
      [
        "5",
        "10"
      ],
      [
        "6",
        "12"
      ],
      [
        "7",
        "14"
      ],
      [
        "8",
        "16"
      ],
      [
        "9",
        "18"
      ],
      [
        "10",
        "20"
      ],
      [
        "11",
        "22"
      ],
      [
        "12",
        "24"
      ],
      [
        "13",
        "26"
      ],
      [
        "14",
        "28"
      ],
      [
        "15",
        "30"
      ],
      [
        "16",
        "32"
      ],
      [
        "17",
        "34"
      ],
      [
        "18",
        "36"
      ],
      [
        "19",
        "38"
      ],
      [
        "20",
        "40"
      ],
      [
        "21",
        "42"
      ],
      [
        "22",
        "44"
      ],
      [
        "23",
        "46"
      ],
      [
        "24",
        "48"
      ],
      [
        "25",
        "50"
      ],
      [
        "26",
        "52"
      ],
      [
        "27",
        "54"
      ],
      [
        "28",
        "56"
      ],
      [
        "29",
        "58"
      ],
      [
        "30",
        "60"
      ],
      [
        "31",
        "62"
      ],
      [
        "32",
        "64"
      ],
      [
        "33",
        "66"
      ],
      [
        "34",
        "68"
      ],
      [
        "35",
        "70"
      ],
      [
        "36",
        "72"
      ],
      [
        "37",
        "74"
      ],
      [
        "38",
        "76"
      ],
      [
        "39",
        "78"
      ],
      [
        "40",
        "80"
      ],
      [
        "41",
        "82"
      ],
      [
        "42",
        "84"
      ],
      [
        "43",
        "86"
      ],
      [
        "44",
        "88"
      ],
      [
        "45",
        "90"
      ],
      [
        "46",
        "92"
      ],
      [
        "47",
        "94"
      ],
      [
        "48",
        "96"
      ],
      [
        "49",
        "98"
      ],
      [
        "50",
        "100"
      ]
    ],
    "faqs": [
      {
        "q": "How many even numbers are there from 1 to 100?",
        "a": "There are 50 even numbers from 1 to 100."
      },
      {
        "q": "Is 0 an even number?",
        "a": "Yes, 0 is considered an even number because it is divisible by 2."
      }
    ]
  },
  {
    "slug": "odd-numbers-1-to-100",
    "title": "Odd Numbers from 1 to 100",
    "category": "Number Lists",
    "intro": "List of all odd numbers from 1 to 100. An odd number is not divisible by 2.",
    "columns": [
      "#",
      "Odd Number"
    ],
    "rows": [
      [
        "1",
        "1"
      ],
      [
        "2",
        "3"
      ],
      [
        "3",
        "5"
      ],
      [
        "4",
        "7"
      ],
      [
        "5",
        "9"
      ],
      [
        "6",
        "11"
      ],
      [
        "7",
        "13"
      ],
      [
        "8",
        "15"
      ],
      [
        "9",
        "17"
      ],
      [
        "10",
        "19"
      ],
      [
        "11",
        "21"
      ],
      [
        "12",
        "23"
      ],
      [
        "13",
        "25"
      ],
      [
        "14",
        "27"
      ],
      [
        "15",
        "29"
      ],
      [
        "16",
        "31"
      ],
      [
        "17",
        "33"
      ],
      [
        "18",
        "35"
      ],
      [
        "19",
        "37"
      ],
      [
        "20",
        "39"
      ],
      [
        "21",
        "41"
      ],
      [
        "22",
        "43"
      ],
      [
        "23",
        "45"
      ],
      [
        "24",
        "47"
      ],
      [
        "25",
        "49"
      ],
      [
        "26",
        "51"
      ],
      [
        "27",
        "53"
      ],
      [
        "28",
        "55"
      ],
      [
        "29",
        "57"
      ],
      [
        "30",
        "59"
      ],
      [
        "31",
        "61"
      ],
      [
        "32",
        "63"
      ],
      [
        "33",
        "65"
      ],
      [
        "34",
        "67"
      ],
      [
        "35",
        "69"
      ],
      [
        "36",
        "71"
      ],
      [
        "37",
        "73"
      ],
      [
        "38",
        "75"
      ],
      [
        "39",
        "77"
      ],
      [
        "40",
        "79"
      ],
      [
        "41",
        "81"
      ],
      [
        "42",
        "83"
      ],
      [
        "43",
        "85"
      ],
      [
        "44",
        "87"
      ],
      [
        "45",
        "89"
      ],
      [
        "46",
        "91"
      ],
      [
        "47",
        "93"
      ],
      [
        "48",
        "95"
      ],
      [
        "49",
        "97"
      ],
      [
        "50",
        "99"
      ]
    ],
    "faqs": [
      {
        "q": "How many odd numbers are there from 1 to 100?",
        "a": "There are 50 odd numbers from 1 to 100."
      },
      {
        "q": "Is 1 an odd number?",
        "a": "Yes, 1 is the first odd number."
      }
    ]
  },
  {
    "slug": "multiplication-tables-21-30",
    "title": "Multiplication Tables 21 to 30",
    "category": "Tables",
    "intro": "Complete multiplication tables from 21 to 30 for quick reference and learning. Essential for building mental maths speed and accuracy.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "21 x 1",
        "21"
      ],
      [
        "21 x 2",
        "42"
      ],
      [
        "21 x 3",
        "63"
      ],
      [
        "21 x 4",
        "84"
      ],
      [
        "21 x 5",
        "105"
      ],
      [
        "22 x 1",
        "22"
      ],
      [
        "22 x 2",
        "44"
      ],
      [
        "22 x 3",
        "66"
      ],
      [
        "22 x 4",
        "88"
      ],
      [
        "22 x 5",
        "110"
      ],
      [
        "25 x 1",
        "25"
      ],
      [
        "25 x 2",
        "50"
      ],
      [
        "25 x 3",
        "75"
      ],
      [
        "25 x 4",
        "100"
      ],
      [
        "25 x 5",
        "125"
      ],
      [
        "30 x 1",
        "30"
      ],
      [
        "30 x 2",
        "60"
      ],
      [
        "30 x 3",
        "90"
      ],
      [
        "30 x 4",
        "120"
      ],
      [
        "30 x 5",
        "150"
      ]
    ],
    "faqs": [
      {
        "q": "How can I remember multiplication tables 21 to 30 easily?",
        "a": "Break each table into chunks of 5 multipliers. Practice one table for 2 minutes daily. Use a notebook to write the table 5 times for muscle memory."
      },
      {
        "q": "Why are tables 25 and 30 important?",
        "a": "Table 25 appears in percentage and decimal calculations. Table 30 is essential for time, money, and measurement conversions commonly used in real life."
      }
    ]
  },
  {
    "slug": "multiplication-tables-31-40",
    "title": "Multiplication Tables 31 to 40",
    "category": "Tables",
    "intro": "Multiplication tables from 31 to 40 designed for intermediate and advanced maths practice. Critical for competitive exams and mental arithmetic.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "31 x 1",
        "31"
      ],
      [
        "31 x 2",
        "62"
      ],
      [
        "31 x 3",
        "93"
      ],
      [
        "31 x 4",
        "124"
      ],
      [
        "31 x 5",
        "155"
      ],
      [
        "35 x 1",
        "35"
      ],
      [
        "35 x 2",
        "70"
      ],
      [
        "35 x 3",
        "105"
      ],
      [
        "35 x 4",
        "140"
      ],
      [
        "35 x 5",
        "175"
      ],
      [
        "36 x 1",
        "36"
      ],
      [
        "36 x 2",
        "72"
      ],
      [
        "36 x 3",
        "108"
      ],
      [
        "36 x 4",
        "144"
      ],
      [
        "36 x 5",
        "180"
      ],
      [
        "40 x 1",
        "40"
      ],
      [
        "40 x 2",
        "80"
      ],
      [
        "40 x 3",
        "120"
      ],
      [
        "40 x 4",
        "160"
      ],
      [
        "40 x 5",
        "200"
      ]
    ],
    "faqs": [
      {
        "q": "Do I need to memorize tables 31 to 40 completely?",
        "a": "For most exams, knowing tables 31 to 40 up to 10 multipliers is sufficient. Practice tables 35, 36, and 40 as they appear frequently in problems."
      },
      {
        "q": "What is the best way to master these tables quickly?",
        "a": "Use the vedic maths technique or pattern recognition. For example, 31 x 11 = 341 (add digits 3+1=4 in the middle). Break problems into smaller chunks."
      }
    ]
  },
  {
    "slug": "cube-roots-1-to-20",
    "title": "Cube Roots 1 to 20",
    "category": "Reference",
    "intro": "Complete chart of cube roots from 1 to 20 for quick reference and calculation. Essential for algebra, geometry, and standardized test preparation.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Cube root of 1",
        "1.00"
      ],
      [
        "Cube root of 8",
        "2.00"
      ],
      [
        "Cube root of 27",
        "3.00"
      ],
      [
        "Cube root of 64",
        "4.00"
      ],
      [
        "Cube root of 125",
        "5.00"
      ],
      [
        "Cube root of 216",
        "6.00"
      ],
      [
        "Cube root of 343",
        "7.00"
      ],
      [
        "Cube root of 512",
        "8.00"
      ],
      [
        "Cube root of 729",
        "9.00"
      ],
      [
        "Cube root of 1000",
        "10.00"
      ],
      [
        "Cube root of 1331",
        "11.00"
      ],
      [
        "Cube root of 1728",
        "12.00"
      ],
      [
        "Cube root of 2197",
        "13.00"
      ],
      [
        "Cube root of 2744",
        "14.00"
      ],
      [
        "Cube root of 3375",
        "15.00"
      ],
      [
        "Cube root of 4096",
        "16.00"
      ],
      [
        "Cube root of 4913",
        "17.00"
      ],
      [
        "Cube root of 5832",
        "18.00"
      ],
      [
        "Cube root of 6859",
        "19.00"
      ],
      [
        "Cube root of 8000",
        "20.00"
      ]
    ],
    "faqs": [
      {
        "q": "What is a perfect cube?",
        "a": "A perfect cube is a number that can be expressed as the product of three equal integers. For example, 8 = 2 x 2 x 2, so 8 is a perfect cube."
      },
      {
        "q": "How do I find the cube root of non-perfect cubes?",
        "a": "For non-perfect cubes, use the prime factorization method or a calculator. For approximation, find the nearest perfect cubes and interpolate between them."
      }
    ]
  },
  {
    "slug": "divisibility-rules-2-to-11",
    "title": "Divisibility Rules 2 to 11",
    "category": "Reference",
    "intro": "Quick reference guide for divisibility rules from 2 to 11. These rules help determine if a number is divisible by another without performing division.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Divisibility by 2",
        "Last digit is even (0, 2, 4, 6, 8)"
      ],
      [
        "Divisibility by 3",
        "Sum of all digits is divisible by 3"
      ],
      [
        "Divisibility by 4",
        "Last two digits form a number divisible by 4"
      ],
      [
        "Divisibility by 5",
        "Last digit is 0 or 5"
      ],
      [
        "Divisibility by 6",
        "Number is divisible by both 2 and 3"
      ],
      [
        "Divisibility by 7",
        "Remove last digit, double it, subtract from rest; repeat until small"
      ],
      [
        "Divisibility by 8",
        "Last three digits form a number divisible by 8"
      ],
      [
        "Divisibility by 9",
        "Sum of all digits is divisible by 9"
      ],
      [
        "Divisibility by 10",
        "Last digit is 0"
      ],
      [
        "Divisibility by 11",
        "Alternating sum of digits (first minus second plus third) is divisible by 11"
      ]
    ],
    "faqs": [
      {
        "q": "How do I use divisibility rules to check if 123456 is divisible by 9?",
        "a": "Add all digits: 1+2+3+4+5+6 = 21. Since 21 is not divisible by 9, 123456 is not divisible by 9."
      },
      {
        "q": "What is the alternating sum method for divisibility by 11?",
        "a": "Starting from the right, subtract and add digits alternately. For 121: 1 - 2 + 1 = 0, which is divisible by 11, so 121 is divisible by 11."
      }
    ]
  },
  {
    "slug": "hcf-lcm-chart-with-examples",
    "title": "HCF and LCM Chart with Examples",
    "category": "Reference",
    "intro": "Complete reference chart for Highest Common Factor (HCF) and Least Common Multiple (LCM) with practical examples. Essential for fraction operations and number theory.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "HCF of 12 and 18",
        "6"
      ],
      [
        "LCM of 12 and 18",
        "36"
      ],
      [
        "HCF of 20 and 30",
        "10"
      ],
      [
        "LCM of 20 and 30",
        "60"
      ],
      [
        "HCF of 36 and 48",
        "12"
      ],
      [
        "LCM of 36 and 48",
        "144"
      ],
      [
        "HCF of 15 and 25",
        "5"
      ],
      [
        "LCM of 15 and 25",
        "75"
      ],
      [
        "HCF of 24 and 36",
        "12"
      ],
      [
        "LCM of 24 and 36",
        "72"
      ],
      [
        "HCF of 16 and 32",
        "16"
      ],
      [
        "LCM of 16 and 32",
        "32"
      ],
      [
        "HCF of 45 and 60",
        "15"
      ],
      [
        "LCM of 45 and 60",
        "180"
      ],
      [
        "HCF of 28 and 42",
        "14"
      ],
      [
        "LCM of 28 and 42",
        "84"
      ],
      [
        "HCF of 50 and 75",
        "25"
      ],
      [
        "LCM of 50 and 75",
        "150"
      ],
      [
        "HCF of 18 and 24",
        "6"
      ],
      [
        "LCM of 18 and 24",
        "72"
      ]
    ],
    "faqs": [
      {
        "q": "How do I find HCF of 12 and 18 using prime factorization?",
        "a": "12 = 2 x 2 x 3 and 18 = 2 x 3 x 3. Common factors are 2 and 3. HCF = 2 x 3 = 6."
      },
      {
        "q": "What is the relationship between HCF and LCM?",
        "a": "For any two numbers, HCF x LCM equals the product of the numbers. For 12 and 18: 6 x 36 = 216, and 12 x 18 = 216."
      }
    ]
  },
  {
    "slug": "fraction-decimal-percentage-conversion",
    "title": "Fraction to Decimal to Percentage Conversion Chart",
    "category": "Conversion",
    "intro": "Quick conversion chart showing equivalent fractions, decimals, and percentages. Essential for comparing quantities and solving percentage problems.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "1/2",
        "0.50 = 50%"
      ],
      [
        "1/3",
        "0.33 = 33.33%"
      ],
      [
        "1/4",
        "0.25 = 25%"
      ],
      [
        "1/5",
        "0.20 = 20%"
      ],
      [
        "1/8",
        "0.125 = 12.5%"
      ],
      [
        "1/10",
        "0.10 = 10%"
      ],
      [
        "3/4",
        "0.75 = 75%"
      ],
      [
        "2/3",
        "0.67 = 66.67%"
      ],
      [
        "3/5",
        "0.60 = 60%"
      ],
      [
        "4/5",
        "0.80 = 80%"
      ],
      [
        "1/6",
        "0.167 = 16.7%"
      ],
      [
        "5/6",
        "0.833 = 83.3%"
      ],
      [
        "1/20",
        "0.05 = 5%"
      ],
      [
        "7/8",
        "0.875 = 87.5%"
      ],
      [
        "2/5",
        "0.40 = 40%"
      ],
      [
        "3/10",
        "0.30 = 30%"
      ],
      [
        "7/10",
        "0.70 = 70%"
      ],
      [
        "1/12",
        "0.083 = 8.33%"
      ],
      [
        "5/12",
        "0.417 = 41.7%"
      ],
      [
        "11/20",
        "0.55 = 55%"
      ]
    ],
    "faqs": [
      {
        "q": "How do I convert 0.375 to a fraction and percentage?",
        "a": "0.375 as a fraction is 3/8 (multiply 0.375 x 1000 to get 375, then divide by 1000 and simplify). As a percentage: 0.375 x 100 = 37.5%."
      },
      {
        "q": "Why is 1/3 equal to 0.33 and not 0.33333?",
        "a": "1/3 = 0.3333... (repeating). For practical use, we round to 0.33 or 33.33%, but technically it continues infinitely."
      }
    ]
  },
  {
    "slug": "place-value-chart-indian-international",
    "title": "Place Value Chart (Indian and International Systems)",
    "category": "Reference",
    "intro": "Comprehensive place value chart showing both Indian and International numeral systems side by side. Essential for understanding large numbers and number names.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Indian: Ones",
        "Units (1)"
      ],
      [
        "Indian: Tens",
        "Tens (10)"
      ],
      [
        "Indian: Hundreds",
        "Hundreds (100)"
      ],
      [
        "Indian: Thousands",
        "Thousands (1,000)"
      ],
      [
        "Indian: Ten Thousands",
        "Ten Thousands (10,000)"
      ],
      [
        "Indian: Lakhs",
        "Lakhs (1,00,000)"
      ],
      [
        "Indian: Ten Lakhs",
        "Ten Lakhs (10,00,000)"
      ],
      [
        "Indian: Crores",
        "Crores (1,00,00,000)"
      ],
      [
        "International: Ones",
        "Units (1)"
      ],
      [
        "International: Tens",
        "Tens (10)"
      ],
      [
        "International: Hundreds",
        "Hundreds (100)"
      ],
      [
        "International: Thousands",
        "Thousands (1,000)"
      ],
      [
        "International: Ten Thousands",
        "Ten Thousands (10,000)"
      ],
      [
        "International: Hundred Thousands",
        "Hundred Thousands (100,000)"
      ],
      [
        "International: Millions",
        "Millions (1,000,000)"
      ],
      [
        "International: Ten Millions",
        "Ten Millions (10,000,000)"
      ],
      [
        "1 Crore (Indian)",
        "10 Million (International)"
      ],
      [
        "1 Lakh (Indian)",
        "100 Thousand (International)"
      ],
      [
        "Example: 5,23,46,789 (Indian)",
        "52,346,789 (International)"
      ],
      [
        "Example: 123,456,789 (International)",
        "12,34,56,789 (Indian)"
      ]
    ],
    "faqs": [
      {
        "q": "How do I read the Indian number 12,34,56,789?",
        "a": "Twelve crore, thirty-four lakh, fifty-six thousand, seven hundred eighty-nine. Break it as 12 (crore) 34 (lakh) 56 (thousand) 789 (units)."
      },
      {
        "q": "What is the difference between Indian and International place value systems?",
        "a": "Indian system groups by 2-3-2-2 (ones, tens, hundreds, thousands, ten thousands, lakh, ten lakh, crore). International groups by 3s (ones, tens, hundreds, thousand, million, billion)."
      }
    ]
  },
  {
    "slug": "metric-conversion-length-mass-capacity",
    "title": "Metric Conversion Chart (Length, Mass, Capacity)",
    "category": "Conversion",
    "intro": "Complete metric and imperial conversion chart for length, mass, and capacity measurements. Ideal for science, cooking, and daily life applications.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "1 kilometre",
        "1000 metres"
      ],
      [
        "1 metre",
        "100 centimetres"
      ],
      [
        "1 centimetre",
        "10 millimetres"
      ],
      [
        "1 inch",
        "2.54 centimetres"
      ],
      [
        "1 foot",
        "12 inches = 30.48 centimetres"
      ],
      [
        "1 yard",
        "3 feet = 0.914 metres"
      ],
      [
        "1 mile",
        "1.609 kilometres"
      ],
      [
        "1 kilogram",
        "1000 grams"
      ],
      [
        "1 gram",
        "1000 milligrams"
      ],
      [
        "1 pound (lb)",
        "453.6 grams"
      ],
      [
        "1 ounce (oz)",
        "28.35 grams"
      ],
      [
        "1 tonne (metric ton)",
        "1000 kilograms"
      ],
      [
        "1 litre",
        "1000 millilitres"
      ],
      [
        "1 millilitre",
        "1 cubic centimetre"
      ],
      [
        "1 gallon (US)",
        "3.785 litres"
      ],
      [
        "1 gallon (UK)",
        "4.546 litres"
      ],
      [
        "1 pint (US)",
        "473.2 millilitres"
      ],
      [
        "1 cup",
        "236.6 millilitres"
      ],
      [
        "1 tablespoon",
        "14.79 millilitres"
      ],
      [
        "1 teaspoon",
        "4.93 millilitres"
      ]
    ],
    "faqs": [
      {
        "q": "How do I convert 5 kilometres to miles?",
        "a": "Divide kilometres by 1.609. So 5 km / 1.609 = 3.11 miles approximately."
      },
      {
        "q": "What is the difference between metric tonne and kilogram?",
        "a": "1 tonne (metric ton) = 1000 kilograms. A tonne is used for measuring large quantities like cargo and coal, while kilogram is for everyday use."
      }
    ]
  },
  {
    "slug": "time-conversion-chart",
    "title": "Time Conversion Chart",
    "category": "Conversion",
    "intro": "Quick reference for time conversions including seconds, minutes, hours, days, weeks, months, and years. Essential for solving speed, distance, and time problems.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "1 minute",
        "60 seconds"
      ],
      [
        "1 hour",
        "60 minutes = 3600 seconds"
      ],
      [
        "1 day",
        "24 hours = 1440 minutes = 86400 seconds"
      ],
      [
        "1 week",
        "7 days = 168 hours"
      ],
      [
        "1 fortnight",
        "14 days = 2 weeks"
      ],
      [
        "1 month",
        "approximately 30 days (28, 29, or 31 days depending on month)"
      ],
      [
        "1 year",
        "12 months = 365 days (366 in leap year)"
      ],
      [
        "1 leap year",
        "366 days (every 4 years, except century years not divisible by 400)"
      ],
      [
        "1 decade",
        "10 years"
      ],
      [
        "1 century",
        "100 years"
      ],
      [
        "12 hours",
        "half day = noon to midnight or midnight to noon"
      ],
      [
        "6 hours",
        "quarter day"
      ],
      [
        "3 hours",
        "180 minutes = 10800 seconds"
      ],
      [
        "30 minutes",
        "1800 seconds = half hour"
      ],
      [
        "15 minutes",
        "900 seconds = quarter hour"
      ],
      [
        "1800 seconds",
        "30 minutes = half hour"
      ],
      [
        "3600 seconds",
        "1 hour"
      ],
      [
        "86400 seconds",
        "24 hours = 1 day"
      ],
      [
        "604800 seconds",
        "1 week"
      ],
      [
        "2592000 seconds",
        "30 days = approximately 1 month"
      ]
    ],
    "faqs": [
      {
        "q": "How many days are there in a regular year and a leap year?",
        "a": "A regular year has 365 days. A leap year has 366 days. Leap years occur every 4 years, but century years must be divisible by 400 to be leap years."
      },
      {
        "q": "How do I convert 2.5 hours to minutes and seconds?",
        "a": "2.5 hours = 2 hours 30 minutes. To convert to seconds: (2 x 3600) + (30 x 60) = 7200 + 1800 = 9000 seconds."
      }
    ]
  },
  {
    "slug": "powers-of-2-and-powers-of-10",
    "title": "Powers of 2 and Powers of 10",
    "category": "Reference",
    "intro": "Complete reference chart for powers of 2 and powers of 10. Essential for binary systems, computer science, and understanding large and small numbers.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "2^0",
        "1"
      ],
      [
        "2^1",
        "2"
      ],
      [
        "2^2",
        "4"
      ],
      [
        "2^3",
        "8"
      ],
      [
        "2^4",
        "16"
      ],
      [
        "2^5",
        "32"
      ],
      [
        "2^6",
        "64"
      ],
      [
        "2^7",
        "128"
      ],
      [
        "2^8",
        "256"
      ],
      [
        "2^9",
        "512"
      ],
      [
        "2^10",
        "1024"
      ],
      [
        "10^0",
        "1"
      ],
      [
        "10^1",
        "10"
      ],
      [
        "10^2",
        "100"
      ],
      [
        "10^3",
        "1000"
      ],
      [
        "10^4",
        "10000"
      ],
      [
        "10^5",
        "100000"
      ],
      [
        "10^6",
        "1000000"
      ],
      [
        "10^-1",
        "0.1"
      ],
      [
        "10^-2",
        "0.01"
      ]
    ],
    "faqs": [
      {
        "q": "Why is 2^10 equal to 1024 and not 1000?",
        "a": "2^10 = 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 = 1024 exactly. In computing, 1024 bytes is called a kilobyte, which is close to but not exactly 1000."
      },
      {
        "q": "What is scientific notation and how do powers of 10 help?",
        "a": "Scientific notation expresses numbers as a decimal between 1 and 10 multiplied by a power of 10. For example, 5000 = 5 x 10^3. Powers of 10 show the magnitude of numbers."
      }
    ]
  },
  {
    "slug": "even-odd-numbers-properties",
    "title": "Even and Odd Numbers Properties",
    "category": "Reference",
    "intro": "Complete guide to even and odd number properties, rules, and practical applications. Essential for understanding number theory and solving divisibility problems.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Definition: Even numbers",
        "Numbers divisible by 2; end in 0, 2, 4, 6, 8"
      ],
      [
        "Definition: Odd numbers",
        "Numbers not divisible by 2; end in 1, 3, 5, 7, 9"
      ],
      [
        "Even + Even",
        "Always Even"
      ],
      [
        "Odd + Odd",
        "Always Even"
      ],
      [
        "Even + Odd",
        "Always Odd"
      ],
      [
        "Even x Even",
        "Always Even"
      ],
      [
        "Odd x Odd",
        "Always Odd"
      ],
      [
        "Even x Odd",
        "Always Even"
      ],
      [
        "Even - Even",
        "Always Even"
      ],
      [
        "Odd - Odd",
        "Always Even"
      ],
      [
        "Even - Odd",
        "Always Odd"
      ],
      [
        "Odd - Even",
        "Always Odd"
      ],
      [
        "Even^Even",
        "Always Even"
      ],
      [
        "Odd^Odd",
        "Always Odd"
      ],
      [
        "Even^Odd",
        "Always Even"
      ],
      [
        "Odd^Even",
        "Always Odd"
      ],
      [
        "Sum of first n even numbers",
        "n(n+1)"
      ],
      [
        "Sum of first n odd numbers",
        "n^2"
      ],
      [
        "Consecutive even numbers",
        "Differ by 2 (e.g., 4, 6, 8)"
      ],
      [
        "Consecutive odd numbers",
        "Differ by 2 (e.g., 3, 5, 7)"
      ]
    ],
    "faqs": [
      {
        "q": "Is zero even or odd?",
        "a": "Zero is even because it is divisible by 2 with no remainder (0 divided by 2 = 0)."
      },
      {
        "q": "What is the sum of the first 10 odd numbers?",
        "a": "Using the formula n^2 where n = 10: 10^2 = 100. You can verify: 1+3+5+7+9+11+13+15+17+19 = 100."
      }
    ]
  },
  {
    "slug": "factors-numbers-1-to-50",
    "title": "Factors of Numbers 1 to 50",
    "category": "Reference",
    "intro": "Comprehensive chart of factors for all numbers from 1 to 50. Useful for finding HCF, LCM, and solving number theory problems.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Factors of 1",
        "1"
      ],
      [
        "Factors of 2",
        "1, 2"
      ],
      [
        "Factors of 3",
        "1, 3"
      ],
      [
        "Factors of 4",
        "1, 2, 4"
      ],
      [
        "Factors of 5",
        "1, 5"
      ],
      [
        "Factors of 6",
        "1, 2, 3, 6"
      ],
      [
        "Factors of 10",
        "1, 2, 5, 10"
      ],
      [
        "Factors of 12",
        "1, 2, 3, 4, 6, 12"
      ],
      [
        "Factors of 15",
        "1, 3, 5, 15"
      ],
      [
        "Factors of 18",
        "1, 2, 3, 6, 9, 18"
      ],
      [
        "Factors of 20",
        "1, 2, 4, 5, 10, 20"
      ],
      [
        "Factors of 24",
        "1, 2, 3, 4, 6, 8, 12, 24"
      ],
      [
        "Factors of 25",
        "1, 5, 25"
      ],
      [
        "Factors of 30",
        "1, 2, 3, 5, 6, 10, 15, 30"
      ],
      [
        "Factors of 36",
        "1, 2, 3, 4, 6, 9, 12, 18, 36"
      ],
      [
        "Factors of 40",
        "1, 2, 4, 5, 8, 10, 20, 40"
      ],
      [
        "Factors of 42",
        "1, 2, 3, 6, 7, 14, 21, 42"
      ],
      [
        "Factors of 48",
        "1, 2, 3, 4, 6, 8, 12, 16, 24, 48"
      ],
      [
        "Factors of 50",
        "1, 2, 5, 10, 25, 50"
      ],
      [
        "Prime numbers up to 50",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47"
      ]
    ],
    "faqs": [
      {
        "q": "How many factors does 36 have?",
        "a": "36 has 9 factors: 1, 2, 3, 4, 6, 9, 12, 18, 36. Count them from the chart or use prime factorization: 36 = 2^2 x 3^2, so number of factors = (2+1)(2+1) = 9."
      },
      {
        "q": "What is the relationship between factors and prime factorization?",
        "a": "Prime factorization breaks a number into prime factors. All other factors are products of combinations of these prime factors. For example, 12 = 2^2 x 3, so factors are 1, 2, 3, 4, 6, 12."
      }
    ]
  },
  {
    "slug": "trigonometric-ratios-standard-angles",
    "title": "Trigonometric Ratios for Standard Angles",
    "category": "Reference",
    "intro": "Essential trigonometric ratios (sin, cos, tan) for standard angles 0, 30, 45, 60, and 90 degrees. Critical for trigonometry, geometry, and physics problems.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "sin(0 degrees)",
        "0"
      ],
      [
        "sin(30 degrees)",
        "1/2"
      ],
      [
        "sin(45 degrees)",
        "sqrt(2)/2 or 1/sqrt(2)"
      ],
      [
        "sin(60 degrees)",
        "sqrt(3)/2"
      ],
      [
        "sin(90 degrees)",
        "1"
      ],
      [
        "cos(0 degrees)",
        "1"
      ],
      [
        "cos(30 degrees)",
        "sqrt(3)/2"
      ],
      [
        "cos(45 degrees)",
        "sqrt(2)/2 or 1/sqrt(2)"
      ],
      [
        "cos(60 degrees)",
        "1/2"
      ],
      [
        "cos(90 degrees)",
        "0"
      ],
      [
        "tan(0 degrees)",
        "0"
      ],
      [
        "tan(30 degrees)",
        "1/sqrt(3) or sqrt(3)/3"
      ],
      [
        "tan(45 degrees)",
        "1"
      ],
      [
        "tan(60 degrees)",
        "sqrt(3)"
      ],
      [
        "tan(90 degrees)",
        "undefined or infinity"
      ],
      [
        "cot(30 degrees)",
        "sqrt(3)"
      ],
      [
        "cot(45 degrees)",
        "1"
      ],
      [
        "cot(60 degrees)",
        "1/sqrt(3)"
      ],
      [
        "sec(0 degrees)",
        "1"
      ],
      [
        "cosec(90 degrees)",
        "1"
      ]
    ],
    "faqs": [
      {
        "q": "How do I remember the sine and cosine values for standard angles?",
        "a": "Use the pattern: sin(0, 30, 45, 60, 90) = 0, 1/2, sqrt(2)/2, sqrt(3)/2, 1. For cosine, reverse the order: 1, sqrt(3)/2, sqrt(2)/2, 1/2, 0."
      },
      {
        "q": "What does it mean that tan(90 degrees) is undefined?",
        "a": "tan(90 degrees) = sin(90)/cos(90) = 1/0, which is undefined. Geometrically, the tangent line is vertical and has no finite slope at 90 degrees."
      }
    ]
  },
  {
    "slug": "algebraic-identities-chart",
    "title": "Algebraic Identities Chart",
    "category": "Formulas",
    "intro": "Complete reference of essential algebraic identities and formulas. Vital for simplifying expressions, factoring, and solving algebraic equations quickly.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "(a + b)^2",
        "a^2 + 2ab + b^2"
      ],
      [
        "(a - b)^2",
        "a^2 - 2ab + b^2"
      ],
      [
        "(a + b)(a - b)",
        "a^2 - b^2"
      ],
      [
        "(a + b)^3",
        "a^3 + 3a^2b + 3ab^2 + b^3"
      ],
      [
        "(a - b)^3",
        "a^3 - 3a^2b + 3ab^2 - b^3"
      ],
      [
        "a^3 + b^3",
        "(a + b)(a^2 - ab + b^2)"
      ],
      [
        "a^3 - b^3",
        "(a - b)(a^2 + ab + b^2)"
      ],
      [
        "(a + b + c)^2",
        "a^2 + b^2 + c^2 + 2ab + 2bc + 2ca"
      ],
      [
        "a^2 + b^2",
        "(a + b)^2 - 2ab"
      ],
      [
        "(x + a)(x + b)",
        "x^2 + (a + b)x + ab"
      ],
      [
        "a^4 - b^4",
        "(a^2 + b^2)(a^2 - b^2)"
      ],
      [
        "a^4 + a^2b^2 + b^4",
        "(a^2 + ab + b^2)(a^2 - ab + b^2)"
      ],
      [
        "(a + b)^2 - (a - b)^2",
        "4ab"
      ],
      [
        "(a + b)^2 + (a - b)^2",
        "2(a^2 + b^2)"
      ],
      [
        "(a + b + c)^3",
        "a^3 + b^3 + c^3 + 3(a + b)(b + c)(c + a)"
      ],
      [
        "a^3 + b^3 + c^3 - 3abc",
        "(a + b + c)(a^2 + b^2 + c^2 - ab - bc - ca)"
      ],
      [
        "(a - b - c)^2",
        "a^2 + b^2 + c^2 - 2ab + 2bc - 2ca"
      ],
      [
        "a^n - b^n",
        "(a - b)(a^(n-1) + a^(n-2)b + ... + ab^(n-2) + b^(n-1))"
      ],
      [
        "(x + y)^2 = x^2 + y^2 if",
        "xy = 0"
      ],
      [
        "x^2 - (a + b)x + ab",
        "(x - a)(x - b)"
      ]
    ],
    "faqs": [
      {
        "q": "How do I expand (a + b + c)^2?",
        "a": "Using the identity: (a + b + c)^2 = a^2 + b^2 + c^2 + 2ab + 2bc + 2ca. You can also expand step by step: (a + b + c)^2 = [(a + b) + c]^2."
      },
      {
        "q": "What is the fastest way to factor a^3 - b^3?",
        "a": "Use the identity: a^3 - b^3 = (a - b)(a^2 + ab + b^2). This is much faster than polynomial long division."
      }
    ]
  },
  {
    "slug": "mensuration-formulas-chart",
    "title": "Mensuration Formulas Chart",
    "category": "Formulas",
    "intro": "Complete mensuration reference covering area, perimeter, surface area, and volume formulas for all common 2D and 3D shapes. Essential for geometry and real-world applications.",
    "columns": [
      "Item",
      "Value"
    ],
    "rows": [
      [
        "Circle Area",
        "π r^2"
      ],
      [
        "Circle Circumference",
        "2π r or π d"
      ],
      [
        "Triangle Area",
        "1/2 x base x height"
      ],
      [
        "Triangle Area (Heron)",
        "sqrt[s(s-a)(s-b)(s-c)] where s = (a+b+c)/2"
      ],
      [
        "Rectangle Area",
        "length x width"
      ],
      [
        "Rectangle Perimeter",
        "2(length + width)"
      ],
      [
        "Square Area",
        "side^2"
      ],
      [
        "Square Perimeter",
        "4 x side"
      ],
      [
        "Parallelogram Area",
        "base x height"
      ],
      [
        "Trapezium Area",
        "1/2 x (sum of parallel sides) x height"
      ],
      [
        "Cube Volume",
        "side^3"
      ],
      [
        "Cube Surface Area",
        "6 x side^2"
      ],
      [
        "Cuboid Volume",
        "length x width x height"
      ],
      [
        "Cuboid Surface Area",
        "2(lw + wh + lh)"
      ],
      [
        "Cylinder Volume",
        "π r^2 h"
      ],
      [
        "Cylinder Surface Area",
        "2π r(r + h)"
      ],
      [
        "Sphere Volume",
        "4/3 π r^3"
      ],
      [
        "Sphere Surface Area",
        "4π r^2"
      ],
      [
        "Cone Volume",
        "1/3 π r^2 h"
      ],
      [
        "Cone Curved Surface Area",
        "π r l where l = sqrt(r^2 + h^2) is slant height"
      ]
    ],
    "faqs": [
      {
        "q": "What is the difference between curved surface area and total surface area of a cone?",
        "a": "Curved surface area of cone = π r l. Total surface area = π r l + π r^2 (curved surface + circular base)."
      },
      {
        "q": "How do I find the surface area of a cylinder?",
        "a": "Surface area of cylinder = 2π r h (curved surface) + 2π r^2 (two circular bases) = 2π r(r + h). Alternatively, 2π r^2 + 2π r h."
      }
    ]
  }
];

export const MT_CATEGORIES = (): string[] => [...new Set(MATHS_TABLES.map((m) => m.category))];
export function getMathRef(slug: string): MathRef | undefined {
  return MATHS_TABLES.find((m) => m.slug === slug);
}
