// AUTO-GENERATED by scripts/ingest-story-decks.mjs — do not edit by hand.
// One entry per uploaded slide deck found in public/story-decks/<class-n-slug>/.
import type { UploadedDeck } from './uploadedDecks';

export const UPLOADED_DECKS: UploadedDeck[] = [];
